// Code generated by protoc-gen-go. DO NOT EDIT.
// source: txdata.proto

package txdata

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Timestamp from public import google/protobuf/timestamp.proto
type Timestamp = timestamp.Timestamp

// 注意: 务必要和各结构体的序号对应起来. 校验的命令如下所示:
// Linux  : grep    "^message" txdata.proto | awk -F" " 'BEGIN{cnt=0}{print"ID_"$2,"= "cnt++";"}'
// Linux  : grep    "^message" txdata.proto
// Windows: findstr "^message" txdata.proto
// 还需要同时修改(ProtoMessage.go)和(m2b.h)
type MsgType int32

const (
	MsgType_Zero1               MsgType = 0
	MsgType_ID_Common1Req       MsgType = 1
	MsgType_ID_Common1Rsp       MsgType = 2
	MsgType_ID_Common2Req       MsgType = 3
	MsgType_ID_Common2Rsp       MsgType = 4
	MsgType_ID_Common2Ack       MsgType = 5
	MsgType_ID_CommonErr        MsgType = 6
	MsgType_ID_ConnectionInfo   MsgType = 7
	MsgType_ID_DisconnectedData MsgType = 8
	MsgType_ID_ConnectReq       MsgType = 9
	MsgType_ID_ConnectRsp       MsgType = 10
	MsgType_ID_OnlineNotice     MsgType = 11
	MsgType_ID_SystemReport     MsgType = 12
	MsgType_ID_EchoItem         MsgType = 13
	MsgType_ID_BinItem          MsgType = 14
	MsgType_ID_EmailItem        MsgType = 15
	MsgType_ID_QryConnInfoReq   MsgType = 16
	MsgType_ID_QryConnInfoRsp   MsgType = 17
	MsgType_ID_QueryRecordReq   MsgType = 18
	MsgType_ID_QueryRecordRsp   MsgType = 19
	MsgType_ID_ExecCmdReq       MsgType = 20
	MsgType_ID_ExecCmdRsp       MsgType = 21
	MsgType_ID_PushWrap         MsgType = 22
	MsgType_ID_PushItem         MsgType = 23
	MsgType_ID_SubscribeReq     MsgType = 24
	MsgType_ID_SubscribeRsp     MsgType = 25
	MsgType_ID_PathwayInfo      MsgType = 26
	MsgType_ID_QrySubscribeReq  MsgType = 27
	MsgType_ID_QrySubscribeRsp  MsgType = 28
)

var MsgType_name = map[int32]string{
	0:  "Zero1",
	1:  "ID_Common1Req",
	2:  "ID_Common1Rsp",
	3:  "ID_Common2Req",
	4:  "ID_Common2Rsp",
	5:  "ID_Common2Ack",
	6:  "ID_CommonErr",
	7:  "ID_ConnectionInfo",
	8:  "ID_DisconnectedData",
	9:  "ID_ConnectReq",
	10: "ID_ConnectRsp",
	11: "ID_OnlineNotice",
	12: "ID_SystemReport",
	13: "ID_EchoItem",
	14: "ID_BinItem",
	15: "ID_EmailItem",
	16: "ID_QryConnInfoReq",
	17: "ID_QryConnInfoRsp",
	18: "ID_QueryRecordReq",
	19: "ID_QueryRecordRsp",
	20: "ID_ExecCmdReq",
	21: "ID_ExecCmdRsp",
	22: "ID_PushWrap",
	23: "ID_PushItem",
	24: "ID_SubscribeReq",
	25: "ID_SubscribeRsp",
	26: "ID_PathwayInfo",
	27: "ID_QrySubscribeReq",
	28: "ID_QrySubscribeRsp",
}
var MsgType_value = map[string]int32{
	"Zero1":               0,
	"ID_Common1Req":       1,
	"ID_Common1Rsp":       2,
	"ID_Common2Req":       3,
	"ID_Common2Rsp":       4,
	"ID_Common2Ack":       5,
	"ID_CommonErr":        6,
	"ID_ConnectionInfo":   7,
	"ID_DisconnectedData": 8,
	"ID_ConnectReq":       9,
	"ID_ConnectRsp":       10,
	"ID_OnlineNotice":     11,
	"ID_SystemReport":     12,
	"ID_EchoItem":         13,
	"ID_BinItem":          14,
	"ID_EmailItem":        15,
	"ID_QryConnInfoReq":   16,
	"ID_QryConnInfoRsp":   17,
	"ID_QueryRecordReq":   18,
	"ID_QueryRecordRsp":   19,
	"ID_ExecCmdReq":       20,
	"ID_ExecCmdRsp":       21,
	"ID_PushWrap":         22,
	"ID_PushItem":         23,
	"ID_SubscribeReq":     24,
	"ID_SubscribeRsp":     25,
	"ID_PathwayInfo":      26,
	"ID_QrySubscribeReq":  27,
	"ID_QrySubscribeRsp":  28,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{0}
}

type ConnectionInfo_LinkType int32

const (
	ConnectionInfo_Zero2   ConnectionInfo_LinkType = 0
	ConnectionInfo_CONNECT ConnectionInfo_LinkType = 1
	ConnectionInfo_ACCEPT  ConnectionInfo_LinkType = 2
)

var ConnectionInfo_LinkType_name = map[int32]string{
	0: "Zero2",
	1: "CONNECT",
	2: "ACCEPT",
}
var ConnectionInfo_LinkType_value = map[string]int32{
	"Zero2":   0,
	"CONNECT": 1,
	"ACCEPT":  2,
}

func (x ConnectionInfo_LinkType) String() string {
	return proto.EnumName(ConnectionInfo_LinkType_name, int32(x))
}
func (ConnectionInfo_LinkType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{7, 0}
}

// 唯一标识一个消息.
type UniKey struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	MsgNo                int64    `protobuf:"varint,2,opt,name=MsgNo,proto3" json:"MsgNo,omitempty"`
	SeqNo                int32    `protobuf:"varint,3,opt,name=SeqNo,proto3" json:"SeqNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UniKey) Reset()         { *m = UniKey{} }
func (m *UniKey) String() string { return proto.CompactTextString(m) }
func (*UniKey) ProtoMessage()    {}
func (*UniKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{0}
}
func (m *UniKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UniKey.Unmarshal(m, b)
}
func (m *UniKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UniKey.Marshal(b, m, deterministic)
}
func (dst *UniKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UniKey.Merge(dst, src)
}
func (m *UniKey) XXX_Size() int {
	return xxx_messageInfo_UniKey.Size(m)
}
func (m *UniKey) XXX_DiscardUnknown() {
	xxx_messageInfo_UniKey.DiscardUnknown(m)
}

var xxx_messageInfo_UniKey proto.InternalMessageInfo

func (m *UniKey) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UniKey) GetMsgNo() int64 {
	if m != nil {
		return m.MsgNo
	}
	return 0
}

func (m *UniKey) GetSeqNo() int32 {
	if m != nil {
		return m.SeqNo
	}
	return 0
}

type Common1Req struct {
	MsgNo                int64                `protobuf:"varint,1,opt,name=MsgNo,proto3" json:"MsgNo,omitempty"`
	SeqNo                int32                `protobuf:"varint,2,opt,name=SeqNo,proto3" json:"SeqNo,omitempty"`
	BatchNo              int64                `protobuf:"varint,3,opt,name=BatchNo,proto3" json:"BatchNo,omitempty"`
	RefNum               int64                `protobuf:"varint,4,opt,name=RefNum,proto3" json:"RefNum,omitempty"`
	RefText              string               `protobuf:"bytes,5,opt,name=RefText,proto3" json:"RefText,omitempty"`
	SenderID             string               `protobuf:"bytes,6,opt,name=SenderID,proto3" json:"SenderID,omitempty"`
	RecverID             string               `protobuf:"bytes,7,opt,name=RecverID,proto3" json:"RecverID,omitempty"`
	ToRoot               bool                 `protobuf:"varint,8,opt,name=ToRoot,proto3" json:"ToRoot,omitempty"`
	IsLog                bool                 `protobuf:"varint,9,opt,name=IsLog,proto3" json:"IsLog,omitempty"`
	IsPush               bool                 `protobuf:"varint,10,opt,name=IsPush,proto3" json:"IsPush,omitempty"`
	ReqType              MsgType              `protobuf:"varint,11,opt,name=ReqType,proto3,enum=txdata.MsgType" json:"ReqType,omitempty"`
	ReqData              []byte               `protobuf:"bytes,12,opt,name=ReqData,proto3" json:"ReqData,omitempty"`
	ReqTime              *timestamp.Timestamp `protobuf:"bytes,13,opt,name=ReqTime,proto3" json:"ReqTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Common1Req) Reset()         { *m = Common1Req{} }
func (m *Common1Req) String() string { return proto.CompactTextString(m) }
func (*Common1Req) ProtoMessage()    {}
func (*Common1Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{1}
}
func (m *Common1Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Common1Req.Unmarshal(m, b)
}
func (m *Common1Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Common1Req.Marshal(b, m, deterministic)
}
func (dst *Common1Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Common1Req.Merge(dst, src)
}
func (m *Common1Req) XXX_Size() int {
	return xxx_messageInfo_Common1Req.Size(m)
}
func (m *Common1Req) XXX_DiscardUnknown() {
	xxx_messageInfo_Common1Req.DiscardUnknown(m)
}

var xxx_messageInfo_Common1Req proto.InternalMessageInfo

func (m *Common1Req) GetMsgNo() int64 {
	if m != nil {
		return m.MsgNo
	}
	return 0
}

func (m *Common1Req) GetSeqNo() int32 {
	if m != nil {
		return m.SeqNo
	}
	return 0
}

func (m *Common1Req) GetBatchNo() int64 {
	if m != nil {
		return m.BatchNo
	}
	return 0
}

func (m *Common1Req) GetRefNum() int64 {
	if m != nil {
		return m.RefNum
	}
	return 0
}

func (m *Common1Req) GetRefText() string {
	if m != nil {
		return m.RefText
	}
	return ""
}

func (m *Common1Req) GetSenderID() string {
	if m != nil {
		return m.SenderID
	}
	return ""
}

func (m *Common1Req) GetRecverID() string {
	if m != nil {
		return m.RecverID
	}
	return ""
}

func (m *Common1Req) GetToRoot() bool {
	if m != nil {
		return m.ToRoot
	}
	return false
}

func (m *Common1Req) GetIsLog() bool {
	if m != nil {
		return m.IsLog
	}
	return false
}

func (m *Common1Req) GetIsPush() bool {
	if m != nil {
		return m.IsPush
	}
	return false
}

func (m *Common1Req) GetReqType() MsgType {
	if m != nil {
		return m.ReqType
	}
	return MsgType_Zero1
}

func (m *Common1Req) GetReqData() []byte {
	if m != nil {
		return m.ReqData
	}
	return nil
}

func (m *Common1Req) GetReqTime() *timestamp.Timestamp {
	if m != nil {
		return m.ReqTime
	}
	return nil
}

type Common1Rsp struct {
	MsgNo                int64                `protobuf:"varint,1,opt,name=MsgNo,proto3" json:"MsgNo,omitempty"`
	SeqNo                int32                `protobuf:"varint,2,opt,name=SeqNo,proto3" json:"SeqNo,omitempty"`
	BatchNo              int64                `protobuf:"varint,3,opt,name=BatchNo,proto3" json:"BatchNo,omitempty"`
	RefNum               int64                `protobuf:"varint,4,opt,name=RefNum,proto3" json:"RefNum,omitempty"`
	RefText              string               `protobuf:"bytes,5,opt,name=RefText,proto3" json:"RefText,omitempty"`
	SenderID             string               `protobuf:"bytes,6,opt,name=SenderID,proto3" json:"SenderID,omitempty"`
	RecverID             string               `protobuf:"bytes,7,opt,name=RecverID,proto3" json:"RecverID,omitempty"`
	ToRoot               bool                 `protobuf:"varint,8,opt,name=ToRoot,proto3" json:"ToRoot,omitempty"`
	IsLog                bool                 `protobuf:"varint,9,opt,name=IsLog,proto3" json:"IsLog,omitempty"`
	IsPush               bool                 `protobuf:"varint,10,opt,name=IsPush,proto3" json:"IsPush,omitempty"`
	RspType              MsgType              `protobuf:"varint,11,opt,name=RspType,proto3,enum=txdata.MsgType" json:"RspType,omitempty"`
	RspData              []byte               `protobuf:"bytes,12,opt,name=RspData,proto3" json:"RspData,omitempty"`
	RspTime              *timestamp.Timestamp `protobuf:"bytes,13,opt,name=RspTime,proto3" json:"RspTime,omitempty"`
	IsLast               bool                 `protobuf:"varint,14,opt,name=IsLast,proto3" json:"IsLast,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Common1Rsp) Reset()         { *m = Common1Rsp{} }
func (m *Common1Rsp) String() string { return proto.CompactTextString(m) }
func (*Common1Rsp) ProtoMessage()    {}
func (*Common1Rsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{2}
}
func (m *Common1Rsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Common1Rsp.Unmarshal(m, b)
}
func (m *Common1Rsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Common1Rsp.Marshal(b, m, deterministic)
}
func (dst *Common1Rsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Common1Rsp.Merge(dst, src)
}
func (m *Common1Rsp) XXX_Size() int {
	return xxx_messageInfo_Common1Rsp.Size(m)
}
func (m *Common1Rsp) XXX_DiscardUnknown() {
	xxx_messageInfo_Common1Rsp.DiscardUnknown(m)
}

var xxx_messageInfo_Common1Rsp proto.InternalMessageInfo

func (m *Common1Rsp) GetMsgNo() int64 {
	if m != nil {
		return m.MsgNo
	}
	return 0
}

func (m *Common1Rsp) GetSeqNo() int32 {
	if m != nil {
		return m.SeqNo
	}
	return 0
}

func (m *Common1Rsp) GetBatchNo() int64 {
	if m != nil {
		return m.BatchNo
	}
	return 0
}

func (m *Common1Rsp) GetRefNum() int64 {
	if m != nil {
		return m.RefNum
	}
	return 0
}

func (m *Common1Rsp) GetRefText() string {
	if m != nil {
		return m.RefText
	}
	return ""
}

func (m *Common1Rsp) GetSenderID() string {
	if m != nil {
		return m.SenderID
	}
	return ""
}

func (m *Common1Rsp) GetRecverID() string {
	if m != nil {
		return m.RecverID
	}
	return ""
}

func (m *Common1Rsp) GetToRoot() bool {
	if m != nil {
		return m.ToRoot
	}
	return false
}

func (m *Common1Rsp) GetIsLog() bool {
	if m != nil {
		return m.IsLog
	}
	return false
}

func (m *Common1Rsp) GetIsPush() bool {
	if m != nil {
		return m.IsPush
	}
	return false
}

func (m *Common1Rsp) GetRspType() MsgType {
	if m != nil {
		return m.RspType
	}
	return MsgType_Zero1
}

func (m *Common1Rsp) GetRspData() []byte {
	if m != nil {
		return m.RspData
	}
	return nil
}

func (m *Common1Rsp) GetRspTime() *timestamp.Timestamp {
	if m != nil {
		return m.RspTime
	}
	return nil
}

func (m *Common1Rsp) GetIsLast() bool {
	if m != nil {
		return m.IsLast
	}
	return false
}

type Common2Req struct {
	Key                  *UniKey              `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	BatchNo              int64                `protobuf:"varint,2,opt,name=BatchNo,proto3" json:"BatchNo,omitempty"`
	RefNum               int64                `protobuf:"varint,3,opt,name=RefNum,proto3" json:"RefNum,omitempty"`
	RefText              string               `protobuf:"bytes,4,opt,name=RefText,proto3" json:"RefText,omitempty"`
	SenderID             string               `protobuf:"bytes,5,opt,name=SenderID,proto3" json:"SenderID,omitempty"`
	RecverID             string               `protobuf:"bytes,6,opt,name=RecverID,proto3" json:"RecverID,omitempty"`
	ToRoot               bool                 `protobuf:"varint,7,opt,name=ToRoot,proto3" json:"ToRoot,omitempty"`
	IsLog                bool                 `protobuf:"varint,8,opt,name=IsLog,proto3" json:"IsLog,omitempty"`
	IsSafe               bool                 `protobuf:"varint,9,opt,name=IsSafe,proto3" json:"IsSafe,omitempty"`
	IsPush               bool                 `protobuf:"varint,10,opt,name=IsPush,proto3" json:"IsPush,omitempty"`
	UpCache              bool                 `protobuf:"varint,11,opt,name=UpCache,proto3" json:"UpCache,omitempty"`
	ReqType              MsgType              `protobuf:"varint,12,opt,name=ReqType,proto3,enum=txdata.MsgType" json:"ReqType,omitempty"`
	ReqData              []byte               `protobuf:"bytes,13,opt,name=ReqData,proto3" json:"ReqData,omitempty"`
	ReqTime              *timestamp.Timestamp `protobuf:"bytes,14,opt,name=ReqTime,proto3" json:"ReqTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Common2Req) Reset()         { *m = Common2Req{} }
func (m *Common2Req) String() string { return proto.CompactTextString(m) }
func (*Common2Req) ProtoMessage()    {}
func (*Common2Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{3}
}
func (m *Common2Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Common2Req.Unmarshal(m, b)
}
func (m *Common2Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Common2Req.Marshal(b, m, deterministic)
}
func (dst *Common2Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Common2Req.Merge(dst, src)
}
func (m *Common2Req) XXX_Size() int {
	return xxx_messageInfo_Common2Req.Size(m)
}
func (m *Common2Req) XXX_DiscardUnknown() {
	xxx_messageInfo_Common2Req.DiscardUnknown(m)
}

var xxx_messageInfo_Common2Req proto.InternalMessageInfo

func (m *Common2Req) GetKey() *UniKey {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Common2Req) GetBatchNo() int64 {
	if m != nil {
		return m.BatchNo
	}
	return 0
}

func (m *Common2Req) GetRefNum() int64 {
	if m != nil {
		return m.RefNum
	}
	return 0
}

func (m *Common2Req) GetRefText() string {
	if m != nil {
		return m.RefText
	}
	return ""
}

func (m *Common2Req) GetSenderID() string {
	if m != nil {
		return m.SenderID
	}
	return ""
}

func (m *Common2Req) GetRecverID() string {
	if m != nil {
		return m.RecverID
	}
	return ""
}

func (m *Common2Req) GetToRoot() bool {
	if m != nil {
		return m.ToRoot
	}
	return false
}

func (m *Common2Req) GetIsLog() bool {
	if m != nil {
		return m.IsLog
	}
	return false
}

func (m *Common2Req) GetIsSafe() bool {
	if m != nil {
		return m.IsSafe
	}
	return false
}

func (m *Common2Req) GetIsPush() bool {
	if m != nil {
		return m.IsPush
	}
	return false
}

func (m *Common2Req) GetUpCache() bool {
	if m != nil {
		return m.UpCache
	}
	return false
}

func (m *Common2Req) GetReqType() MsgType {
	if m != nil {
		return m.ReqType
	}
	return MsgType_Zero1
}

func (m *Common2Req) GetReqData() []byte {
	if m != nil {
		return m.ReqData
	}
	return nil
}

func (m *Common2Req) GetReqTime() *timestamp.Timestamp {
	if m != nil {
		return m.ReqTime
	}
	return nil
}

// 可能出现的情况:SERVER收到了请求结构体,但是解析请求结构体失败,然后不知道怎么赋值响应结构体,便可使用(CommonErr)返回具体错误.
type Common2Rsp struct {
	Key                  *UniKey              `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	BatchNo              int64                `protobuf:"varint,2,opt,name=BatchNo,proto3" json:"BatchNo,omitempty"`
	RefNum               int64                `protobuf:"varint,3,opt,name=RefNum,proto3" json:"RefNum,omitempty"`
	RefText              string               `protobuf:"bytes,4,opt,name=RefText,proto3" json:"RefText,omitempty"`
	SenderID             string               `protobuf:"bytes,5,opt,name=SenderID,proto3" json:"SenderID,omitempty"`
	RecverID             string               `protobuf:"bytes,6,opt,name=RecverID,proto3" json:"RecverID,omitempty"`
	ToRoot               bool                 `protobuf:"varint,7,opt,name=ToRoot,proto3" json:"ToRoot,omitempty"`
	IsLog                bool                 `protobuf:"varint,8,opt,name=IsLog,proto3" json:"IsLog,omitempty"`
	IsSafe               bool                 `protobuf:"varint,9,opt,name=IsSafe,proto3" json:"IsSafe,omitempty"`
	IsPush               bool                 `protobuf:"varint,10,opt,name=IsPush,proto3" json:"IsPush,omitempty"`
	UpCache              bool                 `protobuf:"varint,11,opt,name=UpCache,proto3" json:"UpCache,omitempty"`
	RspType              MsgType              `protobuf:"varint,12,opt,name=RspType,proto3,enum=txdata.MsgType" json:"RspType,omitempty"`
	RspData              []byte               `protobuf:"bytes,13,opt,name=RspData,proto3" json:"RspData,omitempty"`
	RspTime              *timestamp.Timestamp `protobuf:"bytes,14,opt,name=RspTime,proto3" json:"RspTime,omitempty"`
	IsLast               bool                 `protobuf:"varint,15,opt,name=IsLast,proto3" json:"IsLast,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Common2Rsp) Reset()         { *m = Common2Rsp{} }
func (m *Common2Rsp) String() string { return proto.CompactTextString(m) }
func (*Common2Rsp) ProtoMessage()    {}
func (*Common2Rsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{4}
}
func (m *Common2Rsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Common2Rsp.Unmarshal(m, b)
}
func (m *Common2Rsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Common2Rsp.Marshal(b, m, deterministic)
}
func (dst *Common2Rsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Common2Rsp.Merge(dst, src)
}
func (m *Common2Rsp) XXX_Size() int {
	return xxx_messageInfo_Common2Rsp.Size(m)
}
func (m *Common2Rsp) XXX_DiscardUnknown() {
	xxx_messageInfo_Common2Rsp.DiscardUnknown(m)
}

var xxx_messageInfo_Common2Rsp proto.InternalMessageInfo

func (m *Common2Rsp) GetKey() *UniKey {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Common2Rsp) GetBatchNo() int64 {
	if m != nil {
		return m.BatchNo
	}
	return 0
}

func (m *Common2Rsp) GetRefNum() int64 {
	if m != nil {
		return m.RefNum
	}
	return 0
}

func (m *Common2Rsp) GetRefText() string {
	if m != nil {
		return m.RefText
	}
	return ""
}

func (m *Common2Rsp) GetSenderID() string {
	if m != nil {
		return m.SenderID
	}
	return ""
}

func (m *Common2Rsp) GetRecverID() string {
	if m != nil {
		return m.RecverID
	}
	return ""
}

func (m *Common2Rsp) GetToRoot() bool {
	if m != nil {
		return m.ToRoot
	}
	return false
}

func (m *Common2Rsp) GetIsLog() bool {
	if m != nil {
		return m.IsLog
	}
	return false
}

func (m *Common2Rsp) GetIsSafe() bool {
	if m != nil {
		return m.IsSafe
	}
	return false
}

func (m *Common2Rsp) GetIsPush() bool {
	if m != nil {
		return m.IsPush
	}
	return false
}

func (m *Common2Rsp) GetUpCache() bool {
	if m != nil {
		return m.UpCache
	}
	return false
}

func (m *Common2Rsp) GetRspType() MsgType {
	if m != nil {
		return m.RspType
	}
	return MsgType_Zero1
}

func (m *Common2Rsp) GetRspData() []byte {
	if m != nil {
		return m.RspData
	}
	return nil
}

func (m *Common2Rsp) GetRspTime() *timestamp.Timestamp {
	if m != nil {
		return m.RspTime
	}
	return nil
}

func (m *Common2Rsp) GetIsLast() bool {
	if m != nil {
		return m.IsLast
	}
	return false
}

// 对某消息进行确认.
type Common2Ack struct {
	Key                  *UniKey  `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	SenderID             string   `protobuf:"bytes,2,opt,name=SenderID,proto3" json:"SenderID,omitempty"`
	RecverID             string   `protobuf:"bytes,3,opt,name=RecverID,proto3" json:"RecverID,omitempty"`
	ToRoot               bool     `protobuf:"varint,4,opt,name=ToRoot,proto3" json:"ToRoot,omitempty"`
	IsLog                bool     `protobuf:"varint,5,opt,name=IsLog,proto3" json:"IsLog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Common2Ack) Reset()         { *m = Common2Ack{} }
func (m *Common2Ack) String() string { return proto.CompactTextString(m) }
func (*Common2Ack) ProtoMessage()    {}
func (*Common2Ack) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{5}
}
func (m *Common2Ack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Common2Ack.Unmarshal(m, b)
}
func (m *Common2Ack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Common2Ack.Marshal(b, m, deterministic)
}
func (dst *Common2Ack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Common2Ack.Merge(dst, src)
}
func (m *Common2Ack) XXX_Size() int {
	return xxx_messageInfo_Common2Ack.Size(m)
}
func (m *Common2Ack) XXX_DiscardUnknown() {
	xxx_messageInfo_Common2Ack.DiscardUnknown(m)
}

var xxx_messageInfo_Common2Ack proto.InternalMessageInfo

func (m *Common2Ack) GetKey() *UniKey {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Common2Ack) GetSenderID() string {
	if m != nil {
		return m.SenderID
	}
	return ""
}

func (m *Common2Ack) GetRecverID() string {
	if m != nil {
		return m.RecverID
	}
	return ""
}

func (m *Common2Ack) GetToRoot() bool {
	if m != nil {
		return m.ToRoot
	}
	return false
}

func (m *Common2Ack) GetIsLog() bool {
	if m != nil {
		return m.IsLog
	}
	return false
}

// 常用于(Common1Req)和(Common1Rsp)和(Common2Req)和(Common2Rsp)的通信过程中.
type CommonErr struct {
	ErrNo                int32    `protobuf:"varint,1,opt,name=ErrNo,proto3" json:"ErrNo,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonErr) Reset()         { *m = CommonErr{} }
func (m *CommonErr) String() string { return proto.CompactTextString(m) }
func (*CommonErr) ProtoMessage()    {}
func (*CommonErr) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{6}
}
func (m *CommonErr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonErr.Unmarshal(m, b)
}
func (m *CommonErr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonErr.Marshal(b, m, deterministic)
}
func (dst *CommonErr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonErr.Merge(dst, src)
}
func (m *CommonErr) XXX_Size() int {
	return xxx_messageInfo_CommonErr.Size(m)
}
func (m *CommonErr) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonErr.DiscardUnknown(m)
}

var xxx_messageInfo_CommonErr proto.InternalMessageInfo

func (m *CommonErr) GetErrNo() int32 {
	if m != nil {
		return m.ErrNo
	}
	return 0
}

func (m *CommonErr) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type ConnectionInfo struct {
	UserID               string                  `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	BelongID             string                  `protobuf:"bytes,2,opt,name=BelongID,proto3" json:"BelongID,omitempty"`
	Version              string                  `protobuf:"bytes,3,opt,name=Version,proto3" json:"Version,omitempty"`
	LinkMode             ConnectionInfo_LinkType `protobuf:"varint,4,opt,name=LinkMode,proto3,enum=txdata.ConnectionInfo_LinkType" json:"LinkMode,omitempty"`
	ExePid               int32                   `protobuf:"varint,5,opt,name=ExePid,proto3" json:"ExePid,omitempty"`
	ExePath              string                  `protobuf:"bytes,6,opt,name=ExePath,proto3" json:"ExePath,omitempty"`
	Remark               string                  `protobuf:"bytes,7,opt,name=Remark,proto3" json:"Remark,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ConnectionInfo) Reset()         { *m = ConnectionInfo{} }
func (m *ConnectionInfo) String() string { return proto.CompactTextString(m) }
func (*ConnectionInfo) ProtoMessage()    {}
func (*ConnectionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{7}
}
func (m *ConnectionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionInfo.Unmarshal(m, b)
}
func (m *ConnectionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionInfo.Marshal(b, m, deterministic)
}
func (dst *ConnectionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionInfo.Merge(dst, src)
}
func (m *ConnectionInfo) XXX_Size() int {
	return xxx_messageInfo_ConnectionInfo.Size(m)
}
func (m *ConnectionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionInfo proto.InternalMessageInfo

func (m *ConnectionInfo) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ConnectionInfo) GetBelongID() string {
	if m != nil {
		return m.BelongID
	}
	return ""
}

func (m *ConnectionInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ConnectionInfo) GetLinkMode() ConnectionInfo_LinkType {
	if m != nil {
		return m.LinkMode
	}
	return ConnectionInfo_Zero2
}

func (m *ConnectionInfo) GetExePid() int32 {
	if m != nil {
		return m.ExePid
	}
	return 0
}

func (m *ConnectionInfo) GetExePath() string {
	if m != nil {
		return m.ExePath
	}
	return ""
}

func (m *ConnectionInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

type DisconnectedData struct {
	Info                 *ConnectionInfo `protobuf:"bytes,1,opt,name=Info,proto3" json:"Info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DisconnectedData) Reset()         { *m = DisconnectedData{} }
func (m *DisconnectedData) String() string { return proto.CompactTextString(m) }
func (*DisconnectedData) ProtoMessage()    {}
func (*DisconnectedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{8}
}
func (m *DisconnectedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectedData.Unmarshal(m, b)
}
func (m *DisconnectedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectedData.Marshal(b, m, deterministic)
}
func (dst *DisconnectedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectedData.Merge(dst, src)
}
func (m *DisconnectedData) XXX_Size() int {
	return xxx_messageInfo_DisconnectedData.Size(m)
}
func (m *DisconnectedData) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectedData.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectedData proto.InternalMessageInfo

func (m *DisconnectedData) GetInfo() *ConnectionInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ConnectReq struct {
	InfoReq              *ConnectionInfo `protobuf:"bytes,1,opt,name=InfoReq,proto3" json:"InfoReq,omitempty"`
	Pathway              []string        `protobuf:"bytes,2,rep,name=Pathway,proto3" json:"Pathway,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ConnectReq) Reset()         { *m = ConnectReq{} }
func (m *ConnectReq) String() string { return proto.CompactTextString(m) }
func (*ConnectReq) ProtoMessage()    {}
func (*ConnectReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{9}
}
func (m *ConnectReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectReq.Unmarshal(m, b)
}
func (m *ConnectReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectReq.Marshal(b, m, deterministic)
}
func (dst *ConnectReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectReq.Merge(dst, src)
}
func (m *ConnectReq) XXX_Size() int {
	return xxx_messageInfo_ConnectReq.Size(m)
}
func (m *ConnectReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectReq proto.InternalMessageInfo

func (m *ConnectReq) GetInfoReq() *ConnectionInfo {
	if m != nil {
		return m.InfoReq
	}
	return nil
}

func (m *ConnectReq) GetPathway() []string {
	if m != nil {
		return m.Pathway
	}
	return nil
}

type ConnectRsp struct {
	InfoReq              *ConnectionInfo `protobuf:"bytes,1,opt,name=InfoReq,proto3" json:"InfoReq,omitempty"`
	InfoRsp              *ConnectionInfo `protobuf:"bytes,2,opt,name=InfoRsp,proto3" json:"InfoRsp,omitempty"`
	ErrNo                int32           `protobuf:"varint,3,opt,name=ErrNo,proto3" json:"ErrNo,omitempty"`
	ErrMsg               string          `protobuf:"bytes,4,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ConnectRsp) Reset()         { *m = ConnectRsp{} }
func (m *ConnectRsp) String() string { return proto.CompactTextString(m) }
func (*ConnectRsp) ProtoMessage()    {}
func (*ConnectRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{10}
}
func (m *ConnectRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectRsp.Unmarshal(m, b)
}
func (m *ConnectRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectRsp.Marshal(b, m, deterministic)
}
func (dst *ConnectRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectRsp.Merge(dst, src)
}
func (m *ConnectRsp) XXX_Size() int {
	return xxx_messageInfo_ConnectRsp.Size(m)
}
func (m *ConnectRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectRsp proto.InternalMessageInfo

func (m *ConnectRsp) GetInfoReq() *ConnectionInfo {
	if m != nil {
		return m.InfoReq
	}
	return nil
}

func (m *ConnectRsp) GetInfoRsp() *ConnectionInfo {
	if m != nil {
		return m.InfoRsp
	}
	return nil
}

func (m *ConnectRsp) GetErrNo() int32 {
	if m != nil {
		return m.ErrNo
	}
	return 0
}

func (m *ConnectRsp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

// 从(根节点)发往(叶子节点)方向的通知,表达"收到通知的节点,此刻都能和ROOT连通"
type OnlineNotice struct {
	RootIsOnline         bool     `protobuf:"varint,1,opt,name=RootIsOnline,proto3" json:"RootIsOnline,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnlineNotice) Reset()         { *m = OnlineNotice{} }
func (m *OnlineNotice) String() string { return proto.CompactTextString(m) }
func (*OnlineNotice) ProtoMessage()    {}
func (*OnlineNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{11}
}
func (m *OnlineNotice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlineNotice.Unmarshal(m, b)
}
func (m *OnlineNotice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlineNotice.Marshal(b, m, deterministic)
}
func (dst *OnlineNotice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlineNotice.Merge(dst, src)
}
func (m *OnlineNotice) XXX_Size() int {
	return xxx_messageInfo_OnlineNotice.Size(m)
}
func (m *OnlineNotice) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlineNotice.DiscardUnknown(m)
}

var xxx_messageInfo_OnlineNotice proto.InternalMessageInfo

func (m *OnlineNotice) GetRootIsOnline() bool {
	if m != nil {
		return m.RootIsOnline
	}
	return false
}

// 发往(根节点)方向的通知/报告.
type SystemReport struct {
	Level                int32    `protobuf:"varint,1,opt,name=Level,proto3" json:"Level,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Pathway              []string `protobuf:"bytes,3,rep,name=Pathway,proto3" json:"Pathway,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemReport) Reset()         { *m = SystemReport{} }
func (m *SystemReport) String() string { return proto.CompactTextString(m) }
func (*SystemReport) ProtoMessage()    {}
func (*SystemReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{12}
}
func (m *SystemReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemReport.Unmarshal(m, b)
}
func (m *SystemReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemReport.Marshal(b, m, deterministic)
}
func (dst *SystemReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemReport.Merge(dst, src)
}
func (m *SystemReport) XXX_Size() int {
	return xxx_messageInfo_SystemReport.Size(m)
}
func (m *SystemReport) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemReport.DiscardUnknown(m)
}

var xxx_messageInfo_SystemReport proto.InternalMessageInfo

func (m *SystemReport) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *SystemReport) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *SystemReport) GetPathway() []string {
	if m != nil {
		return m.Pathway
	}
	return nil
}

func (m *SystemReport) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type EchoItem struct {
	Data                 string   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	RspCnt               int32    `protobuf:"varint,2,opt,name=RspCnt,proto3" json:"RspCnt,omitempty"`
	SecGap               int32    `protobuf:"varint,3,opt,name=SecGap,proto3" json:"SecGap,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EchoItem) Reset()         { *m = EchoItem{} }
func (m *EchoItem) String() string { return proto.CompactTextString(m) }
func (*EchoItem) ProtoMessage()    {}
func (*EchoItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{13}
}
func (m *EchoItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EchoItem.Unmarshal(m, b)
}
func (m *EchoItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EchoItem.Marshal(b, m, deterministic)
}
func (dst *EchoItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EchoItem.Merge(dst, src)
}
func (m *EchoItem) XXX_Size() int {
	return xxx_messageInfo_EchoItem.Size(m)
}
func (m *EchoItem) XXX_DiscardUnknown() {
	xxx_messageInfo_EchoItem.DiscardUnknown(m)
}

var xxx_messageInfo_EchoItem proto.InternalMessageInfo

func (m *EchoItem) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *EchoItem) GetRspCnt() int32 {
	if m != nil {
		return m.RspCnt
	}
	return 0
}

func (m *EchoItem) GetSecGap() int32 {
	if m != nil {
		return m.SecGap
	}
	return 0
}

// 二进制(想传啥就传啥)
type BinItem struct {
	Type                 int32    `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Data                 [][]byte `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BinItem) Reset()         { *m = BinItem{} }
func (m *BinItem) String() string { return proto.CompactTextString(m) }
func (*BinItem) ProtoMessage()    {}
func (*BinItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{14}
}
func (m *BinItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BinItem.Unmarshal(m, b)
}
func (m *BinItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BinItem.Marshal(b, m, deterministic)
}
func (dst *BinItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BinItem.Merge(dst, src)
}
func (m *BinItem) XXX_Size() int {
	return xxx_messageInfo_BinItem.Size(m)
}
func (m *BinItem) XXX_DiscardUnknown() {
	xxx_messageInfo_BinItem.DiscardUnknown(m)
}

var xxx_messageInfo_BinItem proto.InternalMessageInfo

func (m *BinItem) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *BinItem) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type EmailItem struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	SmtpAddr             string   `protobuf:"bytes,3,opt,name=SmtpAddr,proto3" json:"SmtpAddr,omitempty"`
	To                   string   `protobuf:"bytes,4,opt,name=To,proto3" json:"To,omitempty"`
	Subject              string   `protobuf:"bytes,5,opt,name=Subject,proto3" json:"Subject,omitempty"`
	ContentType          string   `protobuf:"bytes,6,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
	Content              string   `protobuf:"bytes,7,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailItem) Reset()         { *m = EmailItem{} }
func (m *EmailItem) String() string { return proto.CompactTextString(m) }
func (*EmailItem) ProtoMessage()    {}
func (*EmailItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{15}
}
func (m *EmailItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailItem.Unmarshal(m, b)
}
func (m *EmailItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailItem.Marshal(b, m, deterministic)
}
func (dst *EmailItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailItem.Merge(dst, src)
}
func (m *EmailItem) XXX_Size() int {
	return xxx_messageInfo_EmailItem.Size(m)
}
func (m *EmailItem) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailItem.DiscardUnknown(m)
}

var xxx_messageInfo_EmailItem proto.InternalMessageInfo

func (m *EmailItem) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *EmailItem) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *EmailItem) GetSmtpAddr() string {
	if m != nil {
		return m.SmtpAddr
	}
	return ""
}

func (m *EmailItem) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *EmailItem) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *EmailItem) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *EmailItem) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type QryConnInfoReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QryConnInfoReq) Reset()         { *m = QryConnInfoReq{} }
func (m *QryConnInfoReq) String() string { return proto.CompactTextString(m) }
func (*QryConnInfoReq) ProtoMessage()    {}
func (*QryConnInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{16}
}
func (m *QryConnInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QryConnInfoReq.Unmarshal(m, b)
}
func (m *QryConnInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QryConnInfoReq.Marshal(b, m, deterministic)
}
func (dst *QryConnInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QryConnInfoReq.Merge(dst, src)
}
func (m *QryConnInfoReq) XXX_Size() int {
	return xxx_messageInfo_QryConnInfoReq.Size(m)
}
func (m *QryConnInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QryConnInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_QryConnInfoReq proto.InternalMessageInfo

type QryConnInfoRsp struct {
	UserID               string                 `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Cache                map[string]*ConnectReq `protobuf:"bytes,2,rep,name=Cache,proto3" json:"Cache,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *QryConnInfoRsp) Reset()         { *m = QryConnInfoRsp{} }
func (m *QryConnInfoRsp) String() string { return proto.CompactTextString(m) }
func (*QryConnInfoRsp) ProtoMessage()    {}
func (*QryConnInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{17}
}
func (m *QryConnInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QryConnInfoRsp.Unmarshal(m, b)
}
func (m *QryConnInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QryConnInfoRsp.Marshal(b, m, deterministic)
}
func (dst *QryConnInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QryConnInfoRsp.Merge(dst, src)
}
func (m *QryConnInfoRsp) XXX_Size() int {
	return xxx_messageInfo_QryConnInfoRsp.Size(m)
}
func (m *QryConnInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_QryConnInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_QryConnInfoRsp proto.InternalMessageInfo

func (m *QryConnInfoRsp) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *QryConnInfoRsp) GetCache() map[string]*ConnectReq {
	if m != nil {
		return m.Cache
	}
	return nil
}

// 从ROOT查询记录的请求.
type QueryRecordReq struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	SeqNo                int64    `protobuf:"varint,2,opt,name=SeqNo,proto3" json:"SeqNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRecordReq) Reset()         { *m = QueryRecordReq{} }
func (m *QueryRecordReq) String() string { return proto.CompactTextString(m) }
func (*QueryRecordReq) ProtoMessage()    {}
func (*QueryRecordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{18}
}
func (m *QueryRecordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRecordReq.Unmarshal(m, b)
}
func (m *QueryRecordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRecordReq.Marshal(b, m, deterministic)
}
func (dst *QueryRecordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRecordReq.Merge(dst, src)
}
func (m *QueryRecordReq) XXX_Size() int {
	return xxx_messageInfo_QueryRecordReq.Size(m)
}
func (m *QueryRecordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRecordReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRecordReq proto.InternalMessageInfo

func (m *QueryRecordReq) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *QueryRecordReq) GetSeqNo() int64 {
	if m != nil {
		return m.SeqNo
	}
	return 0
}

// 从ROOT查询记录的响应.
type QueryRecordRsp struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	SeqNo                int64    `protobuf:"varint,2,opt,name=SeqNo,proto3" json:"SeqNo,omitempty"`
	Data                 [][]byte `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRecordRsp) Reset()         { *m = QueryRecordRsp{} }
func (m *QueryRecordRsp) String() string { return proto.CompactTextString(m) }
func (*QueryRecordRsp) ProtoMessage()    {}
func (*QueryRecordRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{19}
}
func (m *QueryRecordRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRecordRsp.Unmarshal(m, b)
}
func (m *QueryRecordRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRecordRsp.Marshal(b, m, deterministic)
}
func (dst *QueryRecordRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRecordRsp.Merge(dst, src)
}
func (m *QueryRecordRsp) XXX_Size() int {
	return xxx_messageInfo_QueryRecordRsp.Size(m)
}
func (m *QueryRecordRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRecordRsp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRecordRsp proto.InternalMessageInfo

func (m *QueryRecordRsp) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *QueryRecordRsp) GetSeqNo() int64 {
	if m != nil {
		return m.SeqNo
	}
	return 0
}

func (m *QueryRecordRsp) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// 执行命令的请求.
type ExecCmdReq struct {
	Cmd                  string   `protobuf:"bytes,1,opt,name=Cmd,proto3" json:"Cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecCmdReq) Reset()         { *m = ExecCmdReq{} }
func (m *ExecCmdReq) String() string { return proto.CompactTextString(m) }
func (*ExecCmdReq) ProtoMessage()    {}
func (*ExecCmdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{20}
}
func (m *ExecCmdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecCmdReq.Unmarshal(m, b)
}
func (m *ExecCmdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecCmdReq.Marshal(b, m, deterministic)
}
func (dst *ExecCmdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecCmdReq.Merge(dst, src)
}
func (m *ExecCmdReq) XXX_Size() int {
	return xxx_messageInfo_ExecCmdReq.Size(m)
}
func (m *ExecCmdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecCmdReq.DiscardUnknown(m)
}

var xxx_messageInfo_ExecCmdReq proto.InternalMessageInfo

func (m *ExecCmdReq) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

// 执行命令的响应.
type ExecCmdRsp struct {
	Reply                string   `protobuf:"bytes,1,opt,name=Reply,proto3" json:"Reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecCmdRsp) Reset()         { *m = ExecCmdRsp{} }
func (m *ExecCmdRsp) String() string { return proto.CompactTextString(m) }
func (*ExecCmdRsp) ProtoMessage()    {}
func (*ExecCmdRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{21}
}
func (m *ExecCmdRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecCmdRsp.Unmarshal(m, b)
}
func (m *ExecCmdRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecCmdRsp.Marshal(b, m, deterministic)
}
func (dst *ExecCmdRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecCmdRsp.Merge(dst, src)
}
func (m *ExecCmdRsp) XXX_Size() int {
	return xxx_messageInfo_ExecCmdRsp.Size(m)
}
func (m *ExecCmdRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecCmdRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ExecCmdRsp proto.InternalMessageInfo

func (m *ExecCmdRsp) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

// 推送用途的包装器.
// 建议仅使用(Common1Req)发送推送消息,因为它没有缓存机制.
type PushWrap struct {
	MsgNo                int64                `protobuf:"varint,1,opt,name=MsgNo,proto3" json:"MsgNo,omitempty"`
	UserID               string               `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	MsgTime              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=MsgTime,proto3" json:"MsgTime,omitempty"`
	MsgType              MsgType              `protobuf:"varint,4,opt,name=MsgType,proto3,enum=txdata.MsgType" json:"MsgType,omitempty"`
	MsgData              []byte               `protobuf:"bytes,5,opt,name=MsgData,proto3" json:"MsgData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PushWrap) Reset()         { *m = PushWrap{} }
func (m *PushWrap) String() string { return proto.CompactTextString(m) }
func (*PushWrap) ProtoMessage()    {}
func (*PushWrap) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{22}
}
func (m *PushWrap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushWrap.Unmarshal(m, b)
}
func (m *PushWrap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushWrap.Marshal(b, m, deterministic)
}
func (dst *PushWrap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushWrap.Merge(dst, src)
}
func (m *PushWrap) XXX_Size() int {
	return xxx_messageInfo_PushWrap.Size(m)
}
func (m *PushWrap) XXX_DiscardUnknown() {
	xxx_messageInfo_PushWrap.DiscardUnknown(m)
}

var xxx_messageInfo_PushWrap proto.InternalMessageInfo

func (m *PushWrap) GetMsgNo() int64 {
	if m != nil {
		return m.MsgNo
	}
	return 0
}

func (m *PushWrap) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *PushWrap) GetMsgTime() *timestamp.Timestamp {
	if m != nil {
		return m.MsgTime
	}
	return nil
}

func (m *PushWrap) GetMsgType() MsgType {
	if m != nil {
		return m.MsgType
	}
	return MsgType_Zero1
}

func (m *PushWrap) GetMsgData() []byte {
	if m != nil {
		return m.MsgData
	}
	return nil
}

//
// 推送：
// 谁发的
// 啥时候发的
// 大概内容是什么
// 详细内容是什么
type PushItem struct {
	Subject              string   `protobuf:"bytes,1,opt,name=Subject,proto3" json:"Subject,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	Level                int32    `protobuf:"varint,3,opt,name=Level,proto3" json:"Level,omitempty"`
	Modes                []string `protobuf:"bytes,4,rep,name=Modes,proto3" json:"Modes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushItem) Reset()         { *m = PushItem{} }
func (m *PushItem) String() string { return proto.CompactTextString(m) }
func (*PushItem) ProtoMessage()    {}
func (*PushItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{23}
}
func (m *PushItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushItem.Unmarshal(m, b)
}
func (m *PushItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushItem.Marshal(b, m, deterministic)
}
func (dst *PushItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushItem.Merge(dst, src)
}
func (m *PushItem) XXX_Size() int {
	return xxx_messageInfo_PushItem.Size(m)
}
func (m *PushItem) XXX_DiscardUnknown() {
	xxx_messageInfo_PushItem.DiscardUnknown(m)
}

var xxx_messageInfo_PushItem proto.InternalMessageInfo

func (m *PushItem) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *PushItem) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PushItem) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *PushItem) GetModes() []string {
	if m != nil {
		return m.Modes
	}
	return nil
}

type SubscribeReq struct {
	FromMsgNo            int64    `protobuf:"varint,1,opt,name=FromMsgNo,proto3" json:"FromMsgNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeReq) Reset()         { *m = SubscribeReq{} }
func (m *SubscribeReq) String() string { return proto.CompactTextString(m) }
func (*SubscribeReq) ProtoMessage()    {}
func (*SubscribeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{24}
}
func (m *SubscribeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeReq.Unmarshal(m, b)
}
func (m *SubscribeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeReq.Marshal(b, m, deterministic)
}
func (dst *SubscribeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeReq.Merge(dst, src)
}
func (m *SubscribeReq) XXX_Size() int {
	return xxx_messageInfo_SubscribeReq.Size(m)
}
func (m *SubscribeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeReq.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeReq proto.InternalMessageInfo

func (m *SubscribeReq) GetFromMsgNo() int64 {
	if m != nil {
		return m.FromMsgNo
	}
	return 0
}

type SubscribeRsp struct {
	FromMsgNo            int64    `protobuf:"varint,1,opt,name=FromMsgNo,proto3" json:"FromMsgNo,omitempty"`
	ErrNo                int32    `protobuf:"varint,2,opt,name=ErrNo,proto3" json:"ErrNo,omitempty"`
	ErrMsg               string   `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeRsp) Reset()         { *m = SubscribeRsp{} }
func (m *SubscribeRsp) String() string { return proto.CompactTextString(m) }
func (*SubscribeRsp) ProtoMessage()    {}
func (*SubscribeRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{25}
}
func (m *SubscribeRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRsp.Unmarshal(m, b)
}
func (m *SubscribeRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRsp.Marshal(b, m, deterministic)
}
func (dst *SubscribeRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRsp.Merge(dst, src)
}
func (m *SubscribeRsp) XXX_Size() int {
	return xxx_messageInfo_SubscribeRsp.Size(m)
}
func (m *SubscribeRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRsp proto.InternalMessageInfo

func (m *SubscribeRsp) GetFromMsgNo() int64 {
	if m != nil {
		return m.FromMsgNo
	}
	return 0
}

func (m *SubscribeRsp) GetErrNo() int32 {
	if m != nil {
		return m.ErrNo
	}
	return 0
}

func (m *SubscribeRsp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type PathwayInfo struct {
	UserID               string                          `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Info                 map[string]*PathwayInfo_Pathway `protobuf:"bytes,2,rep,name=Info,proto3" json:"Info,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *PathwayInfo) Reset()         { *m = PathwayInfo{} }
func (m *PathwayInfo) String() string { return proto.CompactTextString(m) }
func (*PathwayInfo) ProtoMessage()    {}
func (*PathwayInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{26}
}
func (m *PathwayInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PathwayInfo.Unmarshal(m, b)
}
func (m *PathwayInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PathwayInfo.Marshal(b, m, deterministic)
}
func (dst *PathwayInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PathwayInfo.Merge(dst, src)
}
func (m *PathwayInfo) XXX_Size() int {
	return xxx_messageInfo_PathwayInfo.Size(m)
}
func (m *PathwayInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PathwayInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PathwayInfo proto.InternalMessageInfo

func (m *PathwayInfo) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *PathwayInfo) GetInfo() map[string]*PathwayInfo_Pathway {
	if m != nil {
		return m.Info
	}
	return nil
}

type PathwayInfo_Pathway struct {
	Data                 []string `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PathwayInfo_Pathway) Reset()         { *m = PathwayInfo_Pathway{} }
func (m *PathwayInfo_Pathway) String() string { return proto.CompactTextString(m) }
func (*PathwayInfo_Pathway) ProtoMessage()    {}
func (*PathwayInfo_Pathway) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{26, 0}
}
func (m *PathwayInfo_Pathway) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PathwayInfo_Pathway.Unmarshal(m, b)
}
func (m *PathwayInfo_Pathway) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PathwayInfo_Pathway.Marshal(b, m, deterministic)
}
func (dst *PathwayInfo_Pathway) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PathwayInfo_Pathway.Merge(dst, src)
}
func (m *PathwayInfo_Pathway) XXX_Size() int {
	return xxx_messageInfo_PathwayInfo_Pathway.Size(m)
}
func (m *PathwayInfo_Pathway) XXX_DiscardUnknown() {
	xxx_messageInfo_PathwayInfo_Pathway.DiscardUnknown(m)
}

var xxx_messageInfo_PathwayInfo_Pathway proto.InternalMessageInfo

func (m *PathwayInfo_Pathway) GetData() []string {
	if m != nil {
		return m.Data
	}
	return nil
}

type QrySubscribeReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QrySubscribeReq) Reset()         { *m = QrySubscribeReq{} }
func (m *QrySubscribeReq) String() string { return proto.CompactTextString(m) }
func (*QrySubscribeReq) ProtoMessage()    {}
func (*QrySubscribeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{27}
}
func (m *QrySubscribeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QrySubscribeReq.Unmarshal(m, b)
}
func (m *QrySubscribeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QrySubscribeReq.Marshal(b, m, deterministic)
}
func (dst *QrySubscribeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QrySubscribeReq.Merge(dst, src)
}
func (m *QrySubscribeReq) XXX_Size() int {
	return xxx_messageInfo_QrySubscribeReq.Size(m)
}
func (m *QrySubscribeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QrySubscribeReq.DiscardUnknown(m)
}

var xxx_messageInfo_QrySubscribeReq proto.InternalMessageInfo

type QrySubscribeRsp struct {
	SubTime              *timestamp.Timestamp `protobuf:"bytes,1,opt,name=SubTime,proto3" json:"SubTime,omitempty"`
	UserID               string               `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	NodeID               string               `protobuf:"bytes,3,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	ToRoot               bool                 `protobuf:"varint,4,opt,name=ToRoot,proto3" json:"ToRoot,omitempty"`
	IsLog                bool                 `protobuf:"varint,5,opt,name=IsLog,proto3" json:"IsLog,omitempty"`
	IsPush               bool                 `protobuf:"varint,6,opt,name=IsPush,proto3" json:"IsPush,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *QrySubscribeRsp) Reset()         { *m = QrySubscribeRsp{} }
func (m *QrySubscribeRsp) String() string { return proto.CompactTextString(m) }
func (*QrySubscribeRsp) ProtoMessage()    {}
func (*QrySubscribeRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ff3c0f6292cf7a0c, []int{28}
}
func (m *QrySubscribeRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QrySubscribeRsp.Unmarshal(m, b)
}
func (m *QrySubscribeRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QrySubscribeRsp.Marshal(b, m, deterministic)
}
func (dst *QrySubscribeRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QrySubscribeRsp.Merge(dst, src)
}
func (m *QrySubscribeRsp) XXX_Size() int {
	return xxx_messageInfo_QrySubscribeRsp.Size(m)
}
func (m *QrySubscribeRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_QrySubscribeRsp.DiscardUnknown(m)
}

var xxx_messageInfo_QrySubscribeRsp proto.InternalMessageInfo

func (m *QrySubscribeRsp) GetSubTime() *timestamp.Timestamp {
	if m != nil {
		return m.SubTime
	}
	return nil
}

func (m *QrySubscribeRsp) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *QrySubscribeRsp) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

func (m *QrySubscribeRsp) GetToRoot() bool {
	if m != nil {
		return m.ToRoot
	}
	return false
}

func (m *QrySubscribeRsp) GetIsLog() bool {
	if m != nil {
		return m.IsLog
	}
	return false
}

func (m *QrySubscribeRsp) GetIsPush() bool {
	if m != nil {
		return m.IsPush
	}
	return false
}

func init() {
	proto.RegisterType((*UniKey)(nil), "txdata.UniKey")
	proto.RegisterType((*Common1Req)(nil), "txdata.Common1Req")
	proto.RegisterType((*Common1Rsp)(nil), "txdata.Common1Rsp")
	proto.RegisterType((*Common2Req)(nil), "txdata.Common2Req")
	proto.RegisterType((*Common2Rsp)(nil), "txdata.Common2Rsp")
	proto.RegisterType((*Common2Ack)(nil), "txdata.Common2Ack")
	proto.RegisterType((*CommonErr)(nil), "txdata.CommonErr")
	proto.RegisterType((*ConnectionInfo)(nil), "txdata.ConnectionInfo")
	proto.RegisterType((*DisconnectedData)(nil), "txdata.DisconnectedData")
	proto.RegisterType((*ConnectReq)(nil), "txdata.ConnectReq")
	proto.RegisterType((*ConnectRsp)(nil), "txdata.ConnectRsp")
	proto.RegisterType((*OnlineNotice)(nil), "txdata.OnlineNotice")
	proto.RegisterType((*SystemReport)(nil), "txdata.SystemReport")
	proto.RegisterType((*EchoItem)(nil), "txdata.EchoItem")
	proto.RegisterType((*BinItem)(nil), "txdata.BinItem")
	proto.RegisterType((*EmailItem)(nil), "txdata.EmailItem")
	proto.RegisterType((*QryConnInfoReq)(nil), "txdata.QryConnInfoReq")
	proto.RegisterType((*QryConnInfoRsp)(nil), "txdata.QryConnInfoRsp")
	proto.RegisterMapType((map[string]*ConnectReq)(nil), "txdata.QryConnInfoRsp.CacheEntry")
	proto.RegisterType((*QueryRecordReq)(nil), "txdata.QueryRecordReq")
	proto.RegisterType((*QueryRecordRsp)(nil), "txdata.QueryRecordRsp")
	proto.RegisterType((*ExecCmdReq)(nil), "txdata.ExecCmdReq")
	proto.RegisterType((*ExecCmdRsp)(nil), "txdata.ExecCmdRsp")
	proto.RegisterType((*PushWrap)(nil), "txdata.PushWrap")
	proto.RegisterType((*PushItem)(nil), "txdata.PushItem")
	proto.RegisterType((*SubscribeReq)(nil), "txdata.SubscribeReq")
	proto.RegisterType((*SubscribeRsp)(nil), "txdata.SubscribeRsp")
	proto.RegisterType((*PathwayInfo)(nil), "txdata.PathwayInfo")
	proto.RegisterMapType((map[string]*PathwayInfo_Pathway)(nil), "txdata.PathwayInfo.InfoEntry")
	proto.RegisterType((*PathwayInfo_Pathway)(nil), "txdata.PathwayInfo.Pathway")
	proto.RegisterType((*QrySubscribeReq)(nil), "txdata.QrySubscribeReq")
	proto.RegisterType((*QrySubscribeRsp)(nil), "txdata.QrySubscribeRsp")
	proto.RegisterEnum("txdata.MsgType", MsgType_name, MsgType_value)
	proto.RegisterEnum("txdata.ConnectionInfo_LinkType", ConnectionInfo_LinkType_name, ConnectionInfo_LinkType_value)
}

func init() { proto.RegisterFile("txdata.proto", fileDescriptor_txdata_ff3c0f6292cf7a0c) }

var fileDescriptor_txdata_ff3c0f6292cf7a0c = []byte{
	// 1550 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0xcd, 0x6f, 0xdb, 0x46,
	0x16, 0x0f, 0x49, 0x7d, 0x3e, 0xc9, 0xf2, 0x78, 0x92, 0x38, 0x5c, 0x25, 0xd9, 0x68, 0x79, 0xd2,
	0x06, 0x0b, 0x65, 0xad, 0x0d, 0xb0, 0x5f, 0x40, 0x00, 0x47, 0x52, 0x0b, 0x21, 0xb6, 0xe2, 0x50,
	0x4a, 0x5b, 0xe4, 0x62, 0xd0, 0xd2, 0x58, 0x56, 0x6c, 0x72, 0x68, 0x0e, 0x95, 0x58, 0xff, 0x47,
	0x73, 0xed, 0xad, 0xe7, 0x1e, 0x7a, 0xce, 0xb1, 0x97, 0x02, 0xfd, 0x93, 0x0a, 0x14, 0xf3, 0x45,
	0x91, 0x8e, 0x64, 0xbb, 0xb9, 0xb6, 0x17, 0x83, 0xbf, 0x37, 0xef, 0x91, 0xef, 0xe3, 0xf7, 0xde,
	0x1b, 0x19, 0xaa, 0xf1, 0xc5, 0xc4, 0x8b, 0xbd, 0x56, 0x18, 0xd1, 0x98, 0xe2, 0x82, 0x44, 0xf5,
	0x47, 0x53, 0x4a, 0xa7, 0x67, 0xe4, 0x89, 0x90, 0x1e, 0xcd, 0x8f, 0x9f, 0xc4, 0x33, 0x9f, 0xb0,
	0xd8, 0xf3, 0x43, 0xa9, 0xe8, 0xec, 0x41, 0xe1, 0x75, 0x30, 0x7b, 0x41, 0x16, 0x78, 0x1b, 0x0a,
	0xaf, 0x19, 0x89, 0xfa, 0x5d, 0xdb, 0x68, 0x18, 0xcd, 0xb2, 0xab, 0x10, 0xbe, 0x03, 0xf9, 0x7d,
	0x36, 0x1d, 0x50, 0xdb, 0x6c, 0x18, 0x4d, 0xcb, 0x95, 0x80, 0x4b, 0x87, 0xe4, 0x7c, 0x40, 0x6d,
	0xab, 0x61, 0x34, 0xf3, 0xae, 0x04, 0xce, 0xaf, 0x26, 0x40, 0x87, 0xfa, 0x3e, 0x0d, 0x76, 0x5c,
	0x72, 0xbe, 0x34, 0x35, 0x56, 0x9a, 0x9a, 0x29, 0x53, 0x6c, 0x43, 0xf1, 0xb9, 0x17, 0x8f, 0x4f,
	0xd4, 0x2b, 0x2d, 0x57, 0x43, 0xee, 0x98, 0x4b, 0x8e, 0x07, 0x73, 0xdf, 0xce, 0x89, 0x03, 0x85,
	0xb8, 0x85, 0x4b, 0x8e, 0x47, 0xe4, 0x22, 0xb6, 0xf3, 0xc2, 0x63, 0x0d, 0x71, 0x1d, 0x4a, 0x43,
	0x12, 0x4c, 0x44, 0x30, 0x05, 0x71, 0x94, 0x60, 0x7e, 0xe6, 0x92, 0xf1, 0x3b, 0x71, 0x56, 0x94,
	0x67, 0x1a, 0xf3, 0x2f, 0x8d, 0xa8, 0x4b, 0x69, 0x6c, 0x97, 0x1a, 0x46, 0xb3, 0xe4, 0x2a, 0xc4,
	0x3d, 0xee, 0xb3, 0x3d, 0x3a, 0xb5, 0xcb, 0x42, 0x2c, 0x01, 0xd7, 0xee, 0xb3, 0x83, 0x39, 0x3b,
	0xb1, 0x41, 0x6a, 0x4b, 0x84, 0xff, 0xce, 0xfd, 0x3a, 0x1f, 0x2d, 0x42, 0x62, 0x57, 0x1a, 0x46,
	0xb3, 0xd6, 0xde, 0x6c, 0xa9, 0xda, 0xec, 0xb3, 0x29, 0x17, 0xbb, 0xfa, 0x5c, 0x86, 0x70, 0xde,
	0xf5, 0x62, 0xcf, 0xae, 0x36, 0x8c, 0x66, 0xd5, 0xd5, 0x10, 0x3f, 0x95, 0x2f, 0x99, 0xf9, 0xc4,
	0xde, 0x68, 0x18, 0xcd, 0x4a, 0xbb, 0xde, 0x92, 0xa5, 0x6c, 0xe9, 0x52, 0xb6, 0x46, 0xba, 0x94,
	0xae, 0x56, 0x75, 0x3e, 0x58, 0xcb, 0xfc, 0xb3, 0xf0, 0x0f, 0x9c, 0x7f, 0x16, 0x5e, 0x9d, 0x7f,
	0x79, 0x2e, 0x42, 0x60, 0x61, 0x26, 0xff, 0x12, 0x8a, 0xfc, 0xb3, 0xf0, 0xc6, 0xf9, 0x97, 0xaa,
	0xd2, 0xa5, 0x3d, 0x8f, 0xc5, 0x76, 0x4d, 0xbb, 0xc4, 0x91, 0xf3, 0x7d, 0x52, 0x97, 0x36, 0xef,
	0x8b, 0x06, 0x58, 0x2f, 0xc8, 0x42, 0x54, 0xa5, 0xd2, 0xae, 0x69, 0xef, 0x64, 0x1f, 0xba, 0xfc,
	0x28, 0x5d, 0x0d, 0x73, 0x5d, 0x35, 0xac, 0x75, 0xd5, 0xc8, 0xad, 0xaf, 0x46, 0xfe, 0x8a, 0x6a,
	0x14, 0xd6, 0x56, 0xa3, 0xb8, 0xba, 0x1a, 0xa5, 0x4f, 0xaa, 0x31, 0xf4, 0x8e, 0x89, 0x2a, 0x92,
	0x42, 0x6b, 0xab, 0x64, 0x43, 0xf1, 0x75, 0xd8, 0xf1, 0xc6, 0x27, 0xb2, 0x4a, 0x25, 0x57, 0xc3,
	0x74, 0xff, 0x54, 0x6f, 0xde, 0x3f, 0x1b, 0x6b, 0xfb, 0xa7, 0x76, 0xf3, 0xfe, 0xf9, 0x98, 0xaa,
	0x13, 0x0b, 0xff, 0xac, 0xd3, 0xb5, 0x75, 0x52, 0x7d, 0x56, 0xbd, 0x79, 0x9f, 0x6d, 0xac, 0xed,
	0xb3, 0xda, 0xe7, 0xf4, 0xd9, 0x66, 0xa6, 0xcf, 0xbe, 0x35, 0x92, 0xfa, 0xed, 0x8e, 0x4f, 0x6f,
	0x50, 0xbf, 0x74, 0xce, 0xcd, 0x2b, 0x72, 0x6e, 0xad, 0xcd, 0x79, 0x6e, 0x75, 0xce, 0xf3, 0xa9,
	0x9c, 0x3b, 0xff, 0x85, 0xb2, 0xf4, 0xaa, 0x17, 0x45, 0x5c, 0xa5, 0x17, 0x45, 0x6a, 0x28, 0xe7,
	0x5d, 0x09, 0xf8, 0x0b, 0x7b, 0x51, 0xb4, 0xcf, 0xa6, 0xca, 0x0d, 0x85, 0x9c, 0x0f, 0x26, 0xd4,
	0x3a, 0x34, 0x08, 0xc8, 0x38, 0x9e, 0xd1, 0xa0, 0x1f, 0x1c, 0xd3, 0xb5, 0x8b, 0xba, 0x0e, 0xa5,
	0xe7, 0xe4, 0x8c, 0x06, 0xd3, 0x65, 0x2c, 0x1a, 0xf3, 0x02, 0x7c, 0x45, 0x22, 0x36, 0xa3, 0x81,
	0x0a, 0x45, 0x43, 0xfc, 0x7f, 0x28, 0xed, 0xcd, 0x82, 0xd3, 0x7d, 0x3a, 0x21, 0x22, 0x96, 0x5a,
	0xfb, 0x91, 0x4e, 0x54, 0xf6, 0xbb, 0x2d, 0xae, 0x26, 0xca, 0x9a, 0x18, 0x08, 0xaf, 0x2f, 0xc8,
	0xc1, 0x6c, 0x22, 0xe2, 0xcd, 0xbb, 0x0a, 0xf1, 0xcf, 0xf1, 0x27, 0x2f, 0x3e, 0x51, 0x6c, 0xd5,
	0x50, 0xb6, 0x85, 0xef, 0x45, 0xa7, 0x6a, 0xf8, 0x2b, 0xe4, 0xb4, 0xa4, 0x1b, 0x82, 0x2d, 0x65,
	0xc8, 0xbf, 0x21, 0x11, 0x6d, 0xa3, 0x5b, 0xb8, 0x02, 0xc5, 0xce, 0xcb, 0xc1, 0xa0, 0xd7, 0x19,
	0x21, 0x03, 0x03, 0x14, 0x76, 0x3b, 0x9d, 0xde, 0xc1, 0x08, 0x99, 0xce, 0x33, 0x40, 0xdd, 0x19,
	0x1b, 0x4b, 0x0f, 0xc9, 0x44, 0x70, 0xe9, 0x31, 0xe4, 0xb8, 0xa3, 0xaa, 0xde, 0xdb, 0xab, 0xc3,
	0x70, 0x85, 0x8e, 0xf3, 0x0d, 0x27, 0x8a, 0x90, 0xf3, 0x81, 0xfc, 0x4f, 0x28, 0x8a, 0x33, 0x72,
	0x7e, 0x8d, 0xb1, 0x56, 0xe3, 0x11, 0xf2, 0x78, 0xde, 0x7b, 0x0b, 0xdb, 0x6c, 0x58, 0x3c, 0x42,
	0x05, 0x9d, 0xef, 0x8c, 0xe5, 0xab, 0x59, 0xf8, 0x19, 0xaf, 0xd6, 0x16, 0x2c, 0x14, 0x65, 0xbc,
	0xce, 0x42, 0xee, 0x79, 0x49, 0x29, 0x6b, 0x35, 0xa5, 0x72, 0x19, 0x4a, 0xb5, 0xa1, 0xfa, 0x32,
	0x38, 0x9b, 0x05, 0x64, 0x40, 0xe3, 0xd9, 0x98, 0x60, 0x07, 0xaa, 0x9c, 0xbb, 0x7d, 0x26, 0xa5,
	0xc2, 0xcd, 0x92, 0x9b, 0x91, 0x39, 0x21, 0x54, 0x87, 0x0b, 0x16, 0x13, 0xdf, 0x25, 0x21, 0x8d,
	0x04, 0xcf, 0xf7, 0xc8, 0x3b, 0x72, 0xa6, 0x49, 0x2c, 0x40, 0x8a, 0x99, 0x66, 0x86, 0x99, 0xa9,
	0x64, 0x59, 0x99, 0x64, 0xf1, 0x93, 0x7d, 0xc2, 0x98, 0x37, 0x25, 0x7a, 0x1a, 0x2a, 0xe8, 0x0c,
	0xa0, 0xd4, 0x1b, 0x9f, 0xd0, 0x7e, 0x4c, 0x7c, 0x8c, 0x21, 0x27, 0x66, 0x87, 0xe4, 0xbb, 0x78,
	0x16, 0x44, 0x62, 0x61, 0x27, 0x88, 0xd5, 0x35, 0x46, 0x21, 0x2e, 0x1f, 0x92, 0xf1, 0x97, 0x5e,
	0xa8, 0x92, 0xa1, 0x90, 0xb3, 0x03, 0xc5, 0xe7, 0xb3, 0x40, 0xbf, 0x4e, 0x4c, 0x2d, 0xe9, 0xbb,
	0x78, 0x4e, 0x3e, 0xc1, 0x8b, 0x59, 0x95, 0x9f, 0x70, 0x7e, 0x32, 0xa0, 0xdc, 0xf3, 0xbd, 0xd9,
	0x99, 0xb0, 0xaa, 0x43, 0x89, 0x87, 0x13, 0x78, 0x3e, 0x51, 0x8e, 0x24, 0x98, 0x9f, 0x1d, 0x78,
	0x8c, 0xbd, 0xa7, 0xd1, 0x44, 0xb7, 0x9e, 0xc6, 0x62, 0xc4, 0xf8, 0x71, 0xb8, 0x3b, 0x99, 0x44,
	0x7a, 0x8c, 0x68, 0x8c, 0x6b, 0x60, 0x8e, 0xa8, 0x8a, 0xdc, 0x1c, 0x89, 0x4b, 0xd8, 0x70, 0x7e,
	0xf4, 0x96, 0x8c, 0x93, 0x2b, 0x95, 0x82, 0xb8, 0x01, 0x95, 0x0e, 0x0d, 0x62, 0x12, 0xc4, 0xc2,
	0x75, 0xd9, 0x55, 0x69, 0x11, 0xb7, 0x55, 0x50, 0xb5, 0x96, 0x86, 0x0e, 0x82, 0xda, 0xab, 0x68,
	0xc1, 0xc9, 0xa3, 0x28, 0xe6, 0xfc, 0x60, 0x64, 0x45, 0x2c, 0x5c, 0x3b, 0x55, 0xfe, 0x0d, 0x79,
	0x39, 0xfd, 0x79, 0x66, 0x2a, 0xed, 0xbf, 0x69, 0x2e, 0x66, 0xcd, 0x5b, 0x42, 0xa7, 0x17, 0xc4,
	0xd1, 0xc2, 0x95, 0xfa, 0xf5, 0x3d, 0x80, 0xa5, 0x10, 0x23, 0xb0, 0x4e, 0xd5, 0x28, 0x2e, 0xbb,
	0xfc, 0x11, 0x37, 0x21, 0xff, 0xce, 0x3b, 0x9b, 0x13, 0x45, 0x72, 0x7c, 0x89, 0xe4, 0x2e, 0x39,
	0x77, 0xa5, 0xc2, 0xff, 0xcc, 0xff, 0x18, 0xce, 0x33, 0xa8, 0xbd, 0x9a, 0x93, 0x68, 0xe1, 0x92,
	0x31, 0x8d, 0x26, 0xbc, 0x4d, 0xae, 0xf8, 0xbd, 0xb2, 0xbc, 0xde, 0x5a, 0xfa, 0x97, 0x89, 0x9b,
	0xb5, 0xbf, 0x22, 0xe0, 0x95, 0xf6, 0x09, 0x3f, 0xac, 0x14, 0x3f, 0xfe, 0x0a, 0xd0, 0xbb, 0x20,
	0xe3, 0x8e, 0x2f, 0xfc, 0x41, 0x60, 0x75, 0xfc, 0x89, 0x8e, 0xb0, 0xe3, 0x4f, 0x1c, 0x67, 0x79,
	0x2e, 0x9b, 0xd4, 0x25, 0xe1, 0x99, 0xce, 0x81, 0x04, 0xce, 0x8f, 0x06, 0x94, 0xf8, 0x9e, 0xfd,
	0x3a, 0xf2, 0xd6, 0xdd, 0xd7, 0xd7, 0x75, 0xd5, 0x53, 0x28, 0xf2, 0x45, 0xcb, 0x57, 0xa7, 0x75,
	0xfd, 0xea, 0x54, 0xaa, 0x7c, 0x6b, 0xab, 0xf5, 0xac, 0xc6, 0xfd, 0xa7, 0x5b, 0x5b, 0x3d, 0x88,
	0xe6, 0x64, 0x53, 0x11, 0x76, 0x5e, 0x6e, 0x6d, 0x05, 0x9d, 0xb7, 0xd2, 0x69, 0xd1, 0x17, 0x29,
	0xce, 0x1a, 0x59, 0xce, 0xa6, 0x18, 0x69, 0x66, 0x18, 0xb9, 0x1c, 0x1f, 0x56, 0x7a, 0x7c, 0xf0,
	0xf0, 0xe9, 0x84, 0x30, 0x3b, 0x27, 0x86, 0x84, 0x04, 0xce, 0x3f, 0xa0, 0x3a, 0x9c, 0x1f, 0xb1,
	0x71, 0x34, 0x3b, 0x22, 0x3c, 0xcf, 0x0f, 0xa0, 0xfc, 0x45, 0x44, 0xfd, 0x74, 0xa2, 0x96, 0x02,
	0xe7, 0x4d, 0x5a, 0x9b, 0x85, 0x57, 0x6b, 0x2f, 0x07, 0xa7, 0xb9, 0x7a, 0x70, 0x5a, 0x99, 0xc1,
	0xf9, 0x8b, 0x01, 0x15, 0x35, 0xb8, 0xae, 0x5c, 0xc4, 0x3b, 0x6a, 0x0f, 0xc9, 0x8e, 0x79, 0xa8,
	0xf3, 0x9b, 0x32, 0x6d, 0xf1, 0x3f, 0xb2, 0x5b, 0x84, 0x6a, 0xfd, 0x61, 0x32, 0x21, 0x53, 0xc3,
	0xce, 0xd2, 0xc3, 0xae, 0x3e, 0x82, 0x72, 0x62, 0xb1, 0xa2, 0x95, 0x76, 0xb2, 0xad, 0x74, 0x7f,
	0xd5, 0x17, 0xd5, 0x73, 0xba, 0xa7, 0xb6, 0x60, 0xf3, 0x55, 0xb4, 0x48, 0x27, 0xd7, 0xf9, 0x68,
	0x5c, 0x92, 0xb1, 0x90, 0xf3, 0x6c, 0x38, 0x3f, 0x12, 0x3c, 0x33, 0xae, 0xe7, 0x99, 0x52, 0x5d,
	0xcb, 0xda, 0x6d, 0x28, 0x0c, 0xe8, 0x84, 0x24, 0x77, 0x2a, 0x85, 0x7e, 0xdf, 0x8d, 0x2a, 0x75,
	0x5b, 0x2d, 0xa4, 0x6f, 0xab, 0x8f, 0x7f, 0xce, 0x25, 0xf4, 0xd6, 0xd7, 0x88, 0x1d, 0x74, 0x0b,
	0x6f, 0xc1, 0x46, 0xbf, 0x7b, 0xb8, 0xfc, 0xcf, 0x04, 0x32, 0x2e, 0x89, 0x58, 0x88, 0xcc, 0x8c,
	0x88, 0xff, 0x4e, 0x43, 0xd6, 0x25, 0x11, 0x0b, 0x51, 0x2e, 0x2b, 0xda, 0x1d, 0x9f, 0xa2, 0x3c,
	0x46, 0x50, 0x4d, 0x44, 0xbd, 0x28, 0x42, 0x05, 0x7c, 0x17, 0xb6, 0x84, 0x24, 0xbd, 0xaf, 0x51,
	0x11, 0xdf, 0x83, 0xdb, 0xfd, 0xee, 0xe1, 0xe5, 0x8b, 0x0b, 0x2a, 0x25, 0x2f, 0xd5, 0xa3, 0x0f,
	0x95, 0x2f, 0x89, 0x58, 0x88, 0x00, 0xdf, 0x86, 0xcd, 0x7e, 0xf7, 0x30, 0xbd, 0xbc, 0x51, 0x45,
	0x09, 0xd3, 0xdb, 0x19, 0x55, 0xf1, 0x26, 0x54, 0xfa, 0xdd, 0x43, 0xbd, 0x40, 0xd1, 0x06, 0xae,
	0x01, 0xf4, 0xbb, 0x87, 0x6a, 0x03, 0xa2, 0x9a, 0x72, 0x39, 0xd9, 0x6e, 0x68, 0x53, 0xb9, 0x9c,
	0x5d, 0x14, 0x08, 0xad, 0x10, 0xb3, 0x10, 0x6d, 0x69, 0x71, 0x66, 0x24, 0x23, 0xbc, 0x42, 0xcc,
	0x42, 0x74, 0x5b, 0xc5, 0xb2, 0x1c, 0x96, 0xe8, 0xce, 0x25, 0x11, 0x0b, 0xd1, 0x5d, 0xe5, 0xb4,
	0x9e, 0x86, 0x68, 0x3b, 0x25, 0x10, 0x3e, 0xde, 0xd3, 0xb1, 0xa6, 0x18, 0x8b, 0xec, 0x4f, 0x84,
	0x2c, 0x44, 0x7f, 0xc1, 0x18, 0x6a, 0xdc, 0x74, 0xd9, 0x00, 0xa8, 0x8e, 0xb7, 0x01, 0xcb, 0x50,
	0x32, 0x2f, 0xb8, 0xbf, 0x4a, 0xce, 0x42, 0xf4, 0xe0, 0xe0, 0xd6, 0x51, 0x41, 0x30, 0xfc, 0x5f,
	0xbf, 0x05, 0x00, 0x00, 0xff, 0xff, 0xd0, 0xe0, 0x41, 0x60, 0x5d, 0x13, 0x00, 0x00,
}
