// Code generated by protoc-gen-go. DO NOT EDIT.
// source: txdata.proto

package txdata

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Timestamp from public import google/protobuf/timestamp.proto
type Timestamp = timestamp.Timestamp

type MsgType int32

const (
	MsgType_Zero1                MsgType = 0
	MsgType_ID_ConnectedData     MsgType = 1
	MsgType_ID_DisconnectedData  MsgType = 2
	MsgType_ID_PushData          MsgType = 3
	MsgType_ID_ExecuteCommandReq MsgType = 31
	MsgType_ID_ExecuteCommandRsp MsgType = 32
	MsgType_ID_ReportDataReq     MsgType = 33
	MsgType_ID_ReportDataRsp     MsgType = 34
)

var MsgType_name = map[int32]string{
	0:  "Zero1",
	1:  "ID_ConnectedData",
	2:  "ID_DisconnectedData",
	3:  "ID_PushData",
	31: "ID_ExecuteCommandReq",
	32: "ID_ExecuteCommandRsp",
	33: "ID_ReportDataReq",
	34: "ID_ReportDataRsp",
}
var MsgType_value = map[string]int32{
	"Zero1":                0,
	"ID_ConnectedData":     1,
	"ID_DisconnectedData":  2,
	"ID_PushData":          3,
	"ID_ExecuteCommandReq": 31,
	"ID_ExecuteCommandRsp": 32,
	"ID_ReportDataReq":     33,
	"ID_ReportDataRsp":     34,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ce08408ec25e7d10, []int{0}
}

type ConnectionInfo_AppType int32

const (
	ConnectionInfo_Zero2  ConnectionInfo_AppType = 0
	ConnectionInfo_SERVER ConnectionInfo_AppType = 1
	ConnectionInfo_AGENT  ConnectionInfo_AppType = 2
)

var ConnectionInfo_AppType_name = map[int32]string{
	0: "Zero2",
	1: "SERVER",
	2: "AGENT",
}
var ConnectionInfo_AppType_value = map[string]int32{
	"Zero2":  0,
	"SERVER": 1,
	"AGENT":  2,
}

func (x ConnectionInfo_AppType) String() string {
	return proto.EnumName(ConnectionInfo_AppType_name, int32(x))
}
func (ConnectionInfo_AppType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ce08408ec25e7d10, []int{0, 0}
}

type ConnectionInfo_LinkType int32

const (
	ConnectionInfo_Zero3   ConnectionInfo_LinkType = 0
	ConnectionInfo_CONNECT ConnectionInfo_LinkType = 1
	ConnectionInfo_ACCEPT  ConnectionInfo_LinkType = 2
)

var ConnectionInfo_LinkType_name = map[int32]string{
	0: "Zero3",
	1: "CONNECT",
	2: "ACCEPT",
}
var ConnectionInfo_LinkType_value = map[string]int32{
	"Zero3":   0,
	"CONNECT": 1,
	"ACCEPT":  2,
}

func (x ConnectionInfo_LinkType) String() string {
	return proto.EnumName(ConnectionInfo_LinkType_name, int32(x))
}
func (ConnectionInfo_LinkType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ce08408ec25e7d10, []int{0, 1}
}

type ConnectionInfo struct {
	UniqueID             string                  `protobuf:"bytes,1,opt,name=UniqueID,proto3" json:"UniqueID,omitempty"`
	BelongID             string                  `protobuf:"bytes,2,opt,name=BelongID,proto3" json:"BelongID,omitempty"`
	Version              string                  `protobuf:"bytes,3,opt,name=Version,proto3" json:"Version,omitempty"`
	ExeType              ConnectionInfo_AppType  `protobuf:"varint,4,opt,name=ExeType,proto3,enum=txdata.ConnectionInfo_AppType" json:"ExeType,omitempty"`
	LinkDir              ConnectionInfo_LinkType `protobuf:"varint,5,opt,name=LinkDir,proto3,enum=txdata.ConnectionInfo_LinkType" json:"LinkDir,omitempty"`
	ExePid               int32                   `protobuf:"varint,6,opt,name=ExePid,proto3" json:"ExePid,omitempty"`
	ExePath              string                  `protobuf:"bytes,7,opt,name=ExePath,proto3" json:"ExePath,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ConnectionInfo) Reset()         { *m = ConnectionInfo{} }
func (m *ConnectionInfo) String() string { return proto.CompactTextString(m) }
func (*ConnectionInfo) ProtoMessage()    {}
func (*ConnectionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ce08408ec25e7d10, []int{0}
}
func (m *ConnectionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionInfo.Unmarshal(m, b)
}
func (m *ConnectionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionInfo.Marshal(b, m, deterministic)
}
func (dst *ConnectionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionInfo.Merge(dst, src)
}
func (m *ConnectionInfo) XXX_Size() int {
	return xxx_messageInfo_ConnectionInfo.Size(m)
}
func (m *ConnectionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionInfo proto.InternalMessageInfo

func (m *ConnectionInfo) GetUniqueID() string {
	if m != nil {
		return m.UniqueID
	}
	return ""
}

func (m *ConnectionInfo) GetBelongID() string {
	if m != nil {
		return m.BelongID
	}
	return ""
}

func (m *ConnectionInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ConnectionInfo) GetExeType() ConnectionInfo_AppType {
	if m != nil {
		return m.ExeType
	}
	return ConnectionInfo_Zero2
}

func (m *ConnectionInfo) GetLinkDir() ConnectionInfo_LinkType {
	if m != nil {
		return m.LinkDir
	}
	return ConnectionInfo_Zero3
}

func (m *ConnectionInfo) GetExePid() int32 {
	if m != nil {
		return m.ExePid
	}
	return 0
}

func (m *ConnectionInfo) GetExePath() string {
	if m != nil {
		return m.ExePath
	}
	return ""
}

type ConnectedData struct {
	Info                 *ConnectionInfo `protobuf:"bytes,1,opt,name=Info,proto3" json:"Info,omitempty"`
	Pathway              []string        `protobuf:"bytes,2,rep,name=Pathway,proto3" json:"Pathway,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ConnectedData) Reset()         { *m = ConnectedData{} }
func (m *ConnectedData) String() string { return proto.CompactTextString(m) }
func (*ConnectedData) ProtoMessage()    {}
func (*ConnectedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ce08408ec25e7d10, []int{1}
}
func (m *ConnectedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectedData.Unmarshal(m, b)
}
func (m *ConnectedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectedData.Marshal(b, m, deterministic)
}
func (dst *ConnectedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectedData.Merge(dst, src)
}
func (m *ConnectedData) XXX_Size() int {
	return xxx_messageInfo_ConnectedData.Size(m)
}
func (m *ConnectedData) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectedData.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectedData proto.InternalMessageInfo

func (m *ConnectedData) GetInfo() *ConnectionInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ConnectedData) GetPathway() []string {
	if m != nil {
		return m.Pathway
	}
	return nil
}

type DisconnectedData struct {
	Info                 *ConnectionInfo `protobuf:"bytes,1,opt,name=Info,proto3" json:"Info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DisconnectedData) Reset()         { *m = DisconnectedData{} }
func (m *DisconnectedData) String() string { return proto.CompactTextString(m) }
func (*DisconnectedData) ProtoMessage()    {}
func (*DisconnectedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ce08408ec25e7d10, []int{2}
}
func (m *DisconnectedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectedData.Unmarshal(m, b)
}
func (m *DisconnectedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectedData.Marshal(b, m, deterministic)
}
func (dst *DisconnectedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectedData.Merge(dst, src)
}
func (m *DisconnectedData) XXX_Size() int {
	return xxx_messageInfo_DisconnectedData.Size(m)
}
func (m *DisconnectedData) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectedData.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectedData proto.InternalMessageInfo

func (m *DisconnectedData) GetInfo() *ConnectionInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ExecuteCommandReq struct {
	RequestID            int64    `protobuf:"varint,1,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	Pathway              []string `protobuf:"bytes,2,rep,name=Pathway,proto3" json:"Pathway,omitempty"`
	Command              string   `protobuf:"bytes,3,opt,name=Command,proto3" json:"Command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteCommandReq) Reset()         { *m = ExecuteCommandReq{} }
func (m *ExecuteCommandReq) String() string { return proto.CompactTextString(m) }
func (*ExecuteCommandReq) ProtoMessage()    {}
func (*ExecuteCommandReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ce08408ec25e7d10, []int{3}
}
func (m *ExecuteCommandReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteCommandReq.Unmarshal(m, b)
}
func (m *ExecuteCommandReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteCommandReq.Marshal(b, m, deterministic)
}
func (dst *ExecuteCommandReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteCommandReq.Merge(dst, src)
}
func (m *ExecuteCommandReq) XXX_Size() int {
	return xxx_messageInfo_ExecuteCommandReq.Size(m)
}
func (m *ExecuteCommandReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteCommandReq.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteCommandReq proto.InternalMessageInfo

func (m *ExecuteCommandReq) GetRequestID() int64 {
	if m != nil {
		return m.RequestID
	}
	return 0
}

func (m *ExecuteCommandReq) GetPathway() []string {
	if m != nil {
		return m.Pathway
	}
	return nil
}

func (m *ExecuteCommandReq) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

type ExecuteCommandRsp struct {
	RequestID            int64    `protobuf:"varint,1,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	UniqueID             string   `protobuf:"bytes,2,opt,name=UniqueID,proto3" json:"UniqueID,omitempty"`
	Result               string   `protobuf:"bytes,3,opt,name=Result,proto3" json:"Result,omitempty"`
	ErrNo                int32    `protobuf:"varint,4,opt,name=ErrNo,proto3" json:"ErrNo,omitempty"`
	ErrMsg               string   `protobuf:"bytes,5,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteCommandRsp) Reset()         { *m = ExecuteCommandRsp{} }
func (m *ExecuteCommandRsp) String() string { return proto.CompactTextString(m) }
func (*ExecuteCommandRsp) ProtoMessage()    {}
func (*ExecuteCommandRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ce08408ec25e7d10, []int{4}
}
func (m *ExecuteCommandRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteCommandRsp.Unmarshal(m, b)
}
func (m *ExecuteCommandRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteCommandRsp.Marshal(b, m, deterministic)
}
func (dst *ExecuteCommandRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteCommandRsp.Merge(dst, src)
}
func (m *ExecuteCommandRsp) XXX_Size() int {
	return xxx_messageInfo_ExecuteCommandRsp.Size(m)
}
func (m *ExecuteCommandRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteCommandRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteCommandRsp proto.InternalMessageInfo

func (m *ExecuteCommandRsp) GetRequestID() int64 {
	if m != nil {
		return m.RequestID
	}
	return 0
}

func (m *ExecuteCommandRsp) GetUniqueID() string {
	if m != nil {
		return m.UniqueID
	}
	return ""
}

func (m *ExecuteCommandRsp) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *ExecuteCommandRsp) GetErrNo() int32 {
	if m != nil {
		return m.ErrNo
	}
	return 0
}

func (m *ExecuteCommandRsp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type ReportDataReq struct {
	RequestID            int64                `protobuf:"varint,1,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	UniqueID             string               `protobuf:"bytes,2,opt,name=UniqueID,proto3" json:"UniqueID,omitempty"`
	SeqNo                int64                `protobuf:"varint,3,opt,name=SeqNo,proto3" json:"SeqNo,omitempty"`
	Topic                string               `protobuf:"bytes,4,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Data                 string               `protobuf:"bytes,5,opt,name=Data,proto3" json:"Data,omitempty"`
	ReportTime           *timestamp.Timestamp `protobuf:"bytes,6,opt,name=ReportTime,proto3" json:"ReportTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReportDataReq) Reset()         { *m = ReportDataReq{} }
func (m *ReportDataReq) String() string { return proto.CompactTextString(m) }
func (*ReportDataReq) ProtoMessage()    {}
func (*ReportDataReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ce08408ec25e7d10, []int{5}
}
func (m *ReportDataReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportDataReq.Unmarshal(m, b)
}
func (m *ReportDataReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportDataReq.Marshal(b, m, deterministic)
}
func (dst *ReportDataReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportDataReq.Merge(dst, src)
}
func (m *ReportDataReq) XXX_Size() int {
	return xxx_messageInfo_ReportDataReq.Size(m)
}
func (m *ReportDataReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportDataReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReportDataReq proto.InternalMessageInfo

func (m *ReportDataReq) GetRequestID() int64 {
	if m != nil {
		return m.RequestID
	}
	return 0
}

func (m *ReportDataReq) GetUniqueID() string {
	if m != nil {
		return m.UniqueID
	}
	return ""
}

func (m *ReportDataReq) GetSeqNo() int64 {
	if m != nil {
		return m.SeqNo
	}
	return 0
}

func (m *ReportDataReq) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *ReportDataReq) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *ReportDataReq) GetReportTime() *timestamp.Timestamp {
	if m != nil {
		return m.ReportTime
	}
	return nil
}

type ReportDataRsp struct {
	RequestID            int64    `protobuf:"varint,1,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	Pathway              []string `protobuf:"bytes,2,rep,name=Pathway,proto3" json:"Pathway,omitempty"`
	SeqNo                int64    `protobuf:"varint,3,opt,name=SeqNo,proto3" json:"SeqNo,omitempty"`
	ErrNo                int32    `protobuf:"varint,4,opt,name=ErrNo,proto3" json:"ErrNo,omitempty"`
	ErrMsg               string   `protobuf:"bytes,5,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportDataRsp) Reset()         { *m = ReportDataRsp{} }
func (m *ReportDataRsp) String() string { return proto.CompactTextString(m) }
func (*ReportDataRsp) ProtoMessage()    {}
func (*ReportDataRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ce08408ec25e7d10, []int{6}
}
func (m *ReportDataRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportDataRsp.Unmarshal(m, b)
}
func (m *ReportDataRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportDataRsp.Marshal(b, m, deterministic)
}
func (dst *ReportDataRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportDataRsp.Merge(dst, src)
}
func (m *ReportDataRsp) XXX_Size() int {
	return xxx_messageInfo_ReportDataRsp.Size(m)
}
func (m *ReportDataRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportDataRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ReportDataRsp proto.InternalMessageInfo

func (m *ReportDataRsp) GetRequestID() int64 {
	if m != nil {
		return m.RequestID
	}
	return 0
}

func (m *ReportDataRsp) GetPathway() []string {
	if m != nil {
		return m.Pathway
	}
	return nil
}

func (m *ReportDataRsp) GetSeqNo() int64 {
	if m != nil {
		return m.SeqNo
	}
	return 0
}

func (m *ReportDataRsp) GetErrNo() int32 {
	if m != nil {
		return m.ErrNo
	}
	return 0
}

func (m *ReportDataRsp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type PushData struct {
	UniqueID             string               `protobuf:"bytes,1,opt,name=UniqueID,proto3" json:"UniqueID,omitempty"`
	Topic                string               `protobuf:"bytes,2,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Data                 string               `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	ReportTime           *timestamp.Timestamp `protobuf:"bytes,4,opt,name=ReportTime,proto3" json:"ReportTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PushData) Reset()         { *m = PushData{} }
func (m *PushData) String() string { return proto.CompactTextString(m) }
func (*PushData) ProtoMessage()    {}
func (*PushData) Descriptor() ([]byte, []int) {
	return fileDescriptor_txdata_ce08408ec25e7d10, []int{7}
}
func (m *PushData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushData.Unmarshal(m, b)
}
func (m *PushData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushData.Marshal(b, m, deterministic)
}
func (dst *PushData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushData.Merge(dst, src)
}
func (m *PushData) XXX_Size() int {
	return xxx_messageInfo_PushData.Size(m)
}
func (m *PushData) XXX_DiscardUnknown() {
	xxx_messageInfo_PushData.DiscardUnknown(m)
}

var xxx_messageInfo_PushData proto.InternalMessageInfo

func (m *PushData) GetUniqueID() string {
	if m != nil {
		return m.UniqueID
	}
	return ""
}

func (m *PushData) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *PushData) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *PushData) GetReportTime() *timestamp.Timestamp {
	if m != nil {
		return m.ReportTime
	}
	return nil
}

func init() {
	proto.RegisterType((*ConnectionInfo)(nil), "txdata.ConnectionInfo")
	proto.RegisterType((*ConnectedData)(nil), "txdata.ConnectedData")
	proto.RegisterType((*DisconnectedData)(nil), "txdata.DisconnectedData")
	proto.RegisterType((*ExecuteCommandReq)(nil), "txdata.ExecuteCommandReq")
	proto.RegisterType((*ExecuteCommandRsp)(nil), "txdata.ExecuteCommandRsp")
	proto.RegisterType((*ReportDataReq)(nil), "txdata.ReportDataReq")
	proto.RegisterType((*ReportDataRsp)(nil), "txdata.ReportDataRsp")
	proto.RegisterType((*PushData)(nil), "txdata.PushData")
	proto.RegisterEnum("txdata.MsgType", MsgType_name, MsgType_value)
	proto.RegisterEnum("txdata.ConnectionInfo_AppType", ConnectionInfo_AppType_name, ConnectionInfo_AppType_value)
	proto.RegisterEnum("txdata.ConnectionInfo_LinkType", ConnectionInfo_LinkType_name, ConnectionInfo_LinkType_value)
}

func init() { proto.RegisterFile("txdata.proto", fileDescriptor_txdata_ce08408ec25e7d10) }

var fileDescriptor_txdata_ce08408ec25e7d10 = []byte{
	// 624 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0x9d, 0xc4, 0x6e, 0x26, 0xb4, 0x2c, 0x4b, 0x54, 0xac, 0x0a, 0xd1, 0xe0, 0x53, 0x55,
	0x24, 0x57, 0xa4, 0x17, 0xe0, 0x80, 0x54, 0x6c, 0x0b, 0x59, 0xa2, 0x21, 0xda, 0xba, 0x3d, 0x70,
	0x89, 0xdc, 0x64, 0x9b, 0x5a, 0x34, 0x5e, 0xc7, 0x5e, 0x8b, 0xf4, 0x1b, 0xe0, 0xc6, 0xaf, 0xf0,
	0x0b, 0xfc, 0x0a, 0xdf, 0x81, 0x76, 0xbd, 0x2e, 0x4d, 0xdb, 0x34, 0x2a, 0x37, 0xbf, 0x99, 0x37,
	0x3b, 0x6f, 0x26, 0x6f, 0x02, 0x8f, 0xf8, 0x7c, 0x1c, 0xf1, 0xc8, 0x49, 0x33, 0xc6, 0x19, 0x36,
	0x4a, 0xb4, 0xb5, 0x3d, 0x61, 0x6c, 0x72, 0x41, 0xf7, 0x64, 0xf4, 0xb4, 0x38, 0xdb, 0xe3, 0xf1,
	0x94, 0xe6, 0x3c, 0x9a, 0xa6, 0x25, 0xd1, 0xfe, 0xa3, 0xc3, 0x86, 0xcb, 0x92, 0x84, 0x8e, 0x78,
	0xcc, 0x92, 0x20, 0x39, 0x63, 0x78, 0x0b, 0xd6, 0x8e, 0x93, 0x78, 0x56, 0xd0, 0xc0, 0xb3, 0xb4,
	0xae, 0xb6, 0xd3, 0x22, 0x57, 0x58, 0xe4, 0x3e, 0xd0, 0x0b, 0x96, 0x4c, 0x02, 0xcf, 0xd2, 0xcb,
	0x5c, 0x85, 0xb1, 0x05, 0xe6, 0x09, 0xcd, 0xf2, 0x98, 0x25, 0x56, 0x5d, 0xa6, 0x2a, 0x88, 0xdf,
	0x80, 0xe9, 0xcf, 0x69, 0x78, 0x99, 0x52, 0xab, 0xd1, 0xd5, 0x76, 0x36, 0x7a, 0x2f, 0x1c, 0xa5,
	0x76, 0xb1, 0xb5, 0x73, 0x90, 0xa6, 0x82, 0x45, 0x2a, 0x3a, 0x7e, 0x0b, 0xe6, 0xa7, 0x38, 0xf9,
	0xea, 0xc5, 0x99, 0xd5, 0x94, 0x95, 0xdb, 0x4b, 0x2a, 0x05, 0xab, 0x2c, 0x55, 0x7c, 0xbc, 0x09,
	0x86, 0x3f, 0xa7, 0x83, 0x78, 0x6c, 0x19, 0x5d, 0x6d, 0xa7, 0x49, 0x14, 0x12, 0x32, 0xc5, 0x57,
	0xc4, 0xcf, 0x2d, 0xb3, 0x94, 0xa9, 0xa0, 0xfd, 0x0a, 0x4c, 0x25, 0x00, 0xb7, 0xa0, 0xf9, 0x85,
	0x66, 0xac, 0x87, 0x6a, 0x18, 0xc0, 0x38, 0xf2, 0xc9, 0x89, 0x4f, 0x90, 0x26, 0xc2, 0x07, 0x1f,
	0xfd, 0x7e, 0x88, 0x74, 0xdb, 0x81, 0xb5, 0xaa, 0x67, 0xc5, 0xde, 0x47, 0x35, 0xdc, 0x06, 0xd3,
	0xfd, 0xdc, 0xef, 0xfb, 0x6e, 0x88, 0x34, 0x51, 0x7a, 0xe0, 0xba, 0xfe, 0x40, 0xf0, 0x8f, 0x61,
	0x5d, 0x49, 0xa6, 0x63, 0x2f, 0xe2, 0x11, 0xde, 0x85, 0x86, 0x50, 0x2e, 0x57, 0xdc, 0xee, 0x6d,
	0xde, 0x3d, 0x17, 0x91, 0x1c, 0xa1, 0x59, 0x28, 0xfc, 0x16, 0x5d, 0x5a, 0x7a, 0xb7, 0x2e, 0x34,
	0x2b, 0x68, 0xbf, 0x07, 0xe4, 0xc5, 0xf9, 0xe8, 0x7f, 0x5f, 0xb6, 0x29, 0x3c, 0xf1, 0xe7, 0x74,
	0x54, 0x70, 0xea, 0xb2, 0xe9, 0x34, 0x4a, 0xc6, 0x84, 0xce, 0xf0, 0x73, 0x68, 0x11, 0x3a, 0x2b,
	0x68, 0xce, 0x95, 0x05, 0xea, 0xe4, 0x5f, 0x60, 0xb9, 0x18, 0x91, 0x51, 0xaf, 0x54, 0x0e, 0x50,
	0xd0, 0xfe, 0xa9, 0xdd, 0xea, 0x93, 0xa7, 0x2b, 0xfa, 0x5c, 0xf7, 0xa1, 0x7e, 0xc3, 0x87, 0x9b,
	0x60, 0x10, 0x9a, 0x17, 0x17, 0x5c, 0x35, 0x52, 0x08, 0x77, 0xa0, 0xe9, 0x67, 0x59, 0x9f, 0x49,
	0x9f, 0x35, 0x49, 0x09, 0xa4, 0x15, 0xb2, 0xec, 0x30, 0x9f, 0x48, 0x13, 0xb5, 0x88, 0x42, 0xf6,
	0x6f, 0x0d, 0xd6, 0x09, 0x4d, 0x59, 0xc6, 0xc5, 0xde, 0x56, 0x4f, 0x7e, 0x9f, 0xa2, 0x0e, 0x34,
	0x8f, 0xe8, 0xac, 0xcf, 0xa4, 0xa0, 0x3a, 0x29, 0x81, 0x88, 0x86, 0x2c, 0x8d, 0x47, 0x52, 0x4f,
	0x8b, 0x94, 0x00, 0x63, 0x68, 0x88, 0x86, 0x4a, 0x8d, 0xfc, 0xc6, 0xef, 0x00, 0x4a, 0x29, 0x61,
	0x3c, 0xa5, 0xd2, 0xb2, 0xed, 0xde, 0x96, 0x53, 0x9e, 0xaf, 0x53, 0x9d, 0xaf, 0x13, 0x56, 0xe7,
	0x4b, 0xae, 0xb1, 0xed, 0xef, 0x8b, 0x73, 0xac, 0xdc, 0xec, 0xf2, 0x5f, 0x70, 0xe9, 0x14, 0x0f,
	0xd8, 0xea, 0x0f, 0x0d, 0xd6, 0x06, 0x45, 0x7e, 0x2e, 0xc7, 0xba, 0xef, 0xcf, 0xe4, 0x6a, 0x39,
	0xfa, 0x5d, 0xcb, 0xa9, 0x2f, 0x5d, 0x4e, 0xe3, 0x21, 0xcb, 0xd9, 0xfd, 0xa5, 0x81, 0x79, 0x98,
	0x4f, 0xae, 0x1f, 0xea, 0x6b, 0x54, 0xc3, 0x1d, 0x40, 0x81, 0x37, 0x5c, 0x38, 0x49, 0xa4, 0xe1,
	0x67, 0xf0, 0x34, 0xf0, 0x86, 0x37, 0x2f, 0x0a, 0xe9, 0xf8, 0x31, 0xb4, 0x03, 0x6f, 0x58, 0x8d,
	0x85, 0xea, 0xd8, 0x82, 0x4e, 0xe0, 0x0d, 0x6f, 0xdd, 0x0e, 0xda, 0xbe, 0x3b, 0x93, 0xa7, 0xa8,
	0xab, 0x7a, 0x2e, 0x38, 0x0e, 0xbd, 0xbc, 0x1d, 0xcd, 0x53, 0x64, 0x0f, 0x6a, 0xa7, 0x86, 0x1c,
	0x6c, 0xff, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x13, 0xdb, 0x76, 0x0e, 0xda, 0x05, 0x00, 0x00,
}
